import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,createModule,createFixture,validateProject,layoutProject} from '../src/core/project.js';
import {blankSize,buildProject} from '../src/core/parts.js';
import {cutListCSV} from '../src/io/cut-list.js';

test('default project is valid',()=>{const p=createProject();assert.equal(validateProject(p),p);assert.equal(p.modules.length,3)});
test('edge banding is deducted from blank size only',()=>assert.deepEqual(blankSize(600,720,[2,2,2,2]),[596,716]));
test('module offsets move module in room',()=>{const p=createProject();p.modules=[createModule('base')];p.modules[0].offsetX=120;p.modules[0].offsetZ=75;const [m]=layoutProject(p);assert.equal(m.x,120);assert.equal(m.z,75)});
test('front can extend beyond cabinet',()=>{const p=createProject();p.modules=[createModule('wall')];p.modules[0].frontOverhangBottom=120;const f=buildProject(p).parts.find(x=>x.role==='front');assert.equal(f.v,836)});
test('door count is configurable',()=>{const p=createProject();p.modules=[createModule('base')];p.modules[0].doorCount=2;assert.equal(buildProject(p).parts.filter(x=>x.role==='front').length,2)});
test('washer is display geometry, not a cut part',()=>{const p=createProject();p.modules=[createModule('washer')];assert.equal(buildProject(p).parts.length,0)});
test('manual countertop length is respected and can raise issue',()=>{const p=createProject();p.modules=[createModule('base')];p.countertop.lengthMode='manual';p.countertop.length=400;p.countertop.offsetX=0;const m=buildProject(p);assert.equal(m.countertop.length,400);assert.ok(m.issues.some(x=>x.type==='countertop-cover'))});
test('out of room module is flagged',()=>{const p=createProject();p.modules=[createModule('base')];p.modules[0].offsetX=2900;const m=buildProject(p);assert.ok(m.issues.some(x=>x.type==='module-out'))});
test('sink fixture is attached to selected cabinet',()=>{const p=createProject();p.modules=[createModule('base')];p.fixtures=[createFixture('sink',p.modules[0].id)];const m=buildProject(p);assert.equal(m.fixtures.length,1);assert.equal(m.fixtures[0].type,'sink')});
test('bottom-under construction changes cut sizes',()=>{const p=createProject();const m=createModule('base');m.bottomMode='under';p.modules=[m];const parts=buildProject(p).parts;assert.equal(parts.find(x=>x.id.endsWith('-BT')).u,600);assert.equal(parts.find(x=>x.id.endsWith('-SL')).v,702)});
test('overlay top spans full wall cabinet width',()=>{const p=createProject();const m=createModule('wall');m.topMode='overlay';p.modules=[m];const parts=buildProject(p).parts;assert.equal(parts.find(x=>x.id.endsWith('-TP')).u,600);assert.equal(parts.find(x=>x.id.endsWith('-SL')).v,702)});
test('shelf count drives cut list',()=>{const p=createProject();const m=createModule('base');m.shelfCount=3;p.modules=[m];assert.equal(buildProject(p).parts.filter(x=>x.id.includes('-SH')).length,3)});
test('edge band type is carried into specification',()=>{const p=createProject();const m=createModule('base');m.bodyEdgeType='PVC';m.bodyEdge=1;p.modules=[m];const side=buildProject(p).parts.find(x=>x.id.endsWith('-SL'));assert.equal(side.edgeType,'PVC');assert.equal(side.edges[1],1)});
test('drawer cabinet creates one front per drawer',()=>{const p=createProject();const m=createModule('drawer');m.drawerCount=4;p.modules=[m];const model=buildProject(p);assert.equal(model.parts.filter(x=>x.role==='front').length,4);assert.ok(model.warnings.some(x=>x.includes('направляющие')))});
test('corner cabinet is available and explicitly preliminary',()=>{const p=createProject();const m=createModule('cornerBase');p.modules=[m];const model=buildProject(p);assert.equal(m.width,900);assert.equal(m.depth,900);assert.ok(model.warnings.some(x=>x.includes('угловой модуль')))});
test('window and door are display-only scene objects',()=>{for(const type of ['window','door']){const p=createProject();p.modules=[createModule(type)];const model=buildProject(p);assert.equal(model.parts.length,0);assert.ok(model.objects.length>=2)}});
test('new appliance variants are display-only',()=>{for(const type of ['microwave','hood','freezer']){const p=createProject();p.modules=[createModule(type)];const model=buildProject(p);assert.equal(model.parts.length,0);assert.ok(model.objects.length>=1)}});
test('CSV contains finished and blank dimensions',()=>{const csv=cutListCSV(buildProject(createProject()).parts);assert.ok(csv.includes('Готовая U мм'));assert.ok(csv.includes('Заготовка U мм'))});
