import test from 'node:test';import assert from 'node:assert/strict';
import {buildCountertopSegments,countertopWall,moduleWorldFootprint} from '../src/core/countertop-segments.js';
import {estimateProjectCost} from '../src/core/cost.js';
const project={room:{width:3000,depth:2500},countertop:{enabled:true,depth:620,thickness:20,elevation:860,overhang:0},costing:{countertopPerM:1000,bodySheetPrice:0,frontSheetPrice:0,backSheetPrice:0,cuttingPerSheet:0,serviceBase:0,edge08PerM:0,edge2PerM:0,hardwareFixed:0,extraCost:0,uncertaintyPercent:0}};
test('wall orientation follows right-angle rotation',()=>{assert.equal(countertopWall(0),'back');assert.equal(countertopWall(90),'left');assert.equal(countertopWall(180),'front');assert.equal(countertopWall(270),'right')});
test('90 degree footprint swaps width and depth around module centre',()=>{const f=moduleWorldFootprint({x:0,z:0,width:600,depth:560,rotationY:90});assert.equal(f.width,560);assert.equal(f.depth,600);assert.equal(f.cx,300);assert.equal(f.cz,280)});
test('L kitchen on back and left walls creates two countertop segments',()=>{const modules=[{id:'a',type:'base',x:700,z:0,width:600,depth:560,rotationY:0},{id:'b',type:'base',x:0,z:700,width:600,depth:560,rotationY:90}];const s=buildCountertopSegments(project,modules);assert.equal(s.length,2);assert.deepEqual(new Set(s.map(x=>x.wall)),new Set(['back','left']));assert.equal(s.find(x=>x.wall==='back').length,600);assert.equal(s.find(x=>x.wall==='left').length,600)});
test('separated runs on same wall stay separate',()=>{const modules=[{id:'a',type:'base',x:0,z:0,width:600,depth:560,rotationY:0},{id:'b',type:'base',x:1200,z:0,width:600,depth:560,rotationY:0}];const s=buildCountertopSegments(project,modules);assert.equal(s.length,2)});
test('cost estimator prices total length of all countertop segments',()=>{const model={parts:[],countertopSegments:[{length:600},{length:900}]};const c=estimateProjectCost(project,model);assert.equal(c.countertopLength,1500);assert.equal(c.countertop,1500);assert.equal(c.total,1500)});
