export type Lang='ru'|'en';
const D={
 ru:{room:'Комната',catalog:'Каталог',project:'Проект',settings:'Настройки',parameters:'Параметры',parts:'Детали',print:'Печать',edit:'Редактировать',copy:'Копировать',remove:'Удалить',width:'Ширина',height:'Высота',depth:'Глубина',length:'Длина',thickness:'Толщина',position:'Положение',materials:'Материалы',facade:'Фасад',handles:'Ручка',legs:'Ножки',doors:'Створок',frontStyle:'Тип фасада',body:'Корпус',countertop:'Столешница',addSink:'Добавить раковину',addHob:'Добавить 2-конфорочную панель',fixtures:'Встраиваемые элементы',alignTo:'Над объектом',offsetX:'Смещение X',offsetZ:'Смещение Z',explode:'Разнести',explodeHint:'Разобранный вид',json:'JSON проекта',csv:'CSV напила',png:'PNG чертёж',pdf:'PDF / печать',theme:'Тема',dark:'Тёмная',light:'Светлая',grid:'Сетка пола',on:'Вкл',off:'Выкл',language:'Язык',view3d:'3D',front:'Фронт',top:'Сверху',objects:'объектов',checks:'проверок',furnitureParts:'деталей',selectObject:'Выбери объект на сцене.',tapHint:'Тап — выбрать · выбранный объект можно сразу тянуть',focusEdit:'Редактировать модуль отдельно',backRoom:'Комната',modulePrint:'PDF / печать модуля',moduleCsv:'CSV модуля',modulePng:'PNG',roomSize:'Размер комнаты',finish:'Отделка',walls:'Стены',floor:'Пол'},
 en:{room:'Room',catalog:'Catalog',project:'Project',settings:'Settings',parameters:'Parameters',parts:'Parts',print:'Print',edit:'Edit',copy:'Copy',remove:'Delete',width:'Width',height:'Height',depth:'Depth',length:'Length',thickness:'Thickness',position:'Position',materials:'Materials',facade:'Front',handles:'Handle',legs:'Legs',doors:'Doors',frontStyle:'Front style',body:'Body',countertop:'Countertop',addSink:'Add sink',addHob:'Add 2-zone hob',fixtures:'Built-in fixtures',alignTo:'Above object',offsetX:'Offset X',offsetZ:'Offset Z',explode:'Explode',explodeHint:'Exploded view',json:'Project JSON',csv:'Cut-list CSV',png:'PNG drawing',pdf:'PDF / print',theme:'Theme',dark:'Dark',light:'Light',grid:'Floor grid',on:'On',off:'Off',language:'Language',view3d:'3D',front:'Front',top:'Top',objects:'objects',checks:'checks',furnitureParts:'parts',selectObject:'Select an object in the scene.',tapHint:'Tap to select · drag the selected object directly',focusEdit:'Edit module separately',backRoom:'Room',modulePrint:'Module PDF / print',moduleCsv:'Module CSV',modulePng:'PNG',roomSize:'Room size',finish:'Finish',walls:'Walls',floor:'Floor'}
} as const;
export type Key=keyof typeof D.ru;export const tr=(lang:Lang,key:Key)=>D[lang][key]||D.ru[key];
const modules={
 ru:{base:'Нижний шкаф',drawer:'Шкаф с ящиками',sink:'Шкаф под раковину',cornerBase:'Угловой нижний шкаф',wall:'Навесной шкаф',cornerWall:'Угловой навесной шкаф',tall:'Пенал',tallOven:'Пенал под духовку',washer:'Стиральная машина',dishwasher:'Посудомоечная машина',oven:'Духовой шкаф',fridge:'Холодильник',freezer:'Морозильник',microwave:'Микроволновая печь',hood:'Вытяжка',window:'Окно',door:'Дверь'},
 en:{base:'Base cabinet',drawer:'Drawer cabinet',sink:'Sink cabinet',cornerBase:'Base corner cabinet',wall:'Wall cabinet',cornerWall:'Wall corner cabinet',tall:'Tall cabinet',tallOven:'Oven tall cabinet',washer:'Washing machine',dishwasher:'Dishwasher',oven:'Oven',fridge:'Refrigerator',freezer:'Freezer',microwave:'Microwave',hood:'Cooker hood',window:'Window',door:'Door'}
} as const;
export const moduleLabel=(lang:Lang,type:string)=>(modules as any)[lang]?.[type]||type;
export const frontLabel=(lang:Lang,key:string)=>({ru:{flat:'Плоский',frame:'Рамочный',glass:'Стекло',slatted:'Рейки',shaker:'Шейкер',handleless:'Без ручки / J-pull',louvered:'Жалюзийный'},en:{flat:'Flat',frame:'Frame',glass:'Glass',slatted:'Slatted',shaker:'Shaker',handleless:'Handleless / J-pull',louvered:'Louvered'}} as any)[lang]?.[key]||key;
export const handleLabel=(lang:Lang,key:string)=>({ru:{bar:'Скоба',knob:'Кнопка',integrated:'Интегрированная',none:'Без ручки'},en:{bar:'Bar',knob:'Knob',integrated:'Integrated',none:'No handle'}} as any)[lang]?.[key]||key;
export const legLabel=(lang:Lang,key:string)=>({ru:{round:'Круглые',square:'Квадратные',hidden:'Скрытые/цоколь'},en:{round:'Round',square:'Square',hidden:'Hidden/plinth'}} as any)[lang]?.[key]||key;
