import { cutListCSV } from '../../src/io/cut-list.js';
import { MODULE_TYPES,SUBSTRATES,DECORS } from '../../src/catalog/materials.js';
import { explodedCentre } from '../domain/view-math.js';

const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const safe=(s:string)=>s.replace(/[^a-z0-9а-яё._-]+/gi,'-').replace(/^-+|-+$/g,'')||'kitchen-cad';
const blobDownload=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),15000)};
export const downloadJson=(project:any)=>blobDownload(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),`${safe(project.name||'kitchen')}.json`);
export const downloadCsv=(model:any,moduleId?:string)=>{const parts=moduleId?model.parts.filter((p:any)=>p.moduleId===moduleId):model.parts;blobDownload(new Blob([cutListCSV(parts)],{type:'text/csv;charset=utf-8'}),`${moduleId?'module-cut-list':'project-cut-list'}.csv`)};

function overviewSvg(project:any,model:any){const modules=model.modules||[],W=920,H=430,pad=55,maxX=Math.max(project.room.width,...modules.map((m:any)=>m.x+m.width),1),maxY=Math.max(project.room.height,...modules.map((m:any)=>m.y+m.height),1),s=Math.min((W-2*pad)/maxX,(H-2*pad)/maxY);const rects=modules.map((m:any)=>{const x=pad+m.x*s,y=H-pad-(m.y+m.height)*s,w=Math.max(2,m.width*s),h=Math.max(2,m.height*s);return `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${['washer','dishwasher','oven','fridge'].includes(m.type)?'#d9dee0':'#e8e4da'}" stroke="#35515a"/><text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" font-size="12">${esc(MODULE_TYPES[m.type]||m.type)}</text><text x="${x+w/2}" y="${y+h/2+16}" text-anchor="middle" font-size="10">${m.width}×${m.height}</text></g>`}).join('');return `<svg viewBox="0 0 ${W} ${H}" class="drawing"><rect width="100%" height="100%" fill="#fff"/><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="#88979c"/>${rects}<text x="${pad}" y="25" font-size="18" font-weight="700">Общий фронтальный вид</text><text x="${pad}" y="45" font-size="11">Комната ${project.room.width} × ${project.room.depth} × ${project.room.height} мм</text></svg>`}

function moduleSvg(model:any,module:any,explode=140){const objects=model.parts.filter((p:any)=>p.moduleId===module.id);const W=920,H=470,pad=80;const positioned=objects.map((o:any)=>({...o,drawCenter:explodedCentre(o,module,explode)}));const xs=positioned.flatMap((o:any)=>[o.drawCenter[0]-o.size[0]/2,o.drawCenter[0]+o.size[0]/2]),ys=positioned.flatMap((o:any)=>[o.drawCenter[1]-o.size[1]/2,o.drawCenter[1]+o.size[1]/2]);const minX=Math.min(module.x,...xs),maxX=Math.max(module.x+module.width,...xs),minY=Math.min(module.y,...ys),maxY=Math.max(module.y+module.height,...ys),s=Math.min((W-2*pad)/Math.max(1,maxX-minX),(H-2*pad)/Math.max(1,maxY-minY));const shapes=positioned.map((o:any,i:number)=>{const x=pad+(o.drawCenter[0]-o.size[0]/2-minX)*s,y=H-pad-(o.drawCenter[1]+o.size[1]/2-minY)*s,w=Math.max(2,o.size[0]*s),h=Math.max(2,o.size[1]*s);return `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${o.role==='front'?'#dce7d7':'#efece3'}" stroke="#566a70"/><circle cx="${x+w/2}" cy="${y+h/2}" r="11" fill="#6549c9"/><text x="${x+w/2}" y="${y+h/2+4}" text-anchor="middle" font-size="10" fill="#fff" font-weight="700">${i+1}</text></g>`}).join('');return `<svg viewBox="0 0 ${W} ${H}" class="drawing"><rect width="100%" height="100%" fill="#fff"/><text x="${pad}" y="25" font-size="18" font-weight="700">${esc(MODULE_TYPES[module.type]||module.type)} — разобранный вид</text><text x="${pad}" y="46" font-size="12">Габарит: ${module.width} × ${module.height} × ${module.depth} мм · разнос ${explode} мм</text>${shapes}</svg>`}

function partsTable(parts:any[]){return `<table><thead><tr><th>#</th><th>ID</th><th>Деталь</th><th>Материал</th><th>Готовый размер, мм</th><th>Заготовка, мм</th><th>Кромка</th></tr></thead><tbody>${parts.map((p:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(SUBSTRATES[p.substrate]?.name||p.substrate)} / ${esc(DECORS[p.decor]?.name||p.decor)}</td><td>${p.u} × ${p.v} × ${p.thickness}</td><td>${p.blankU} × ${p.blankV} × ${p.thickness}</td><td>${p.edges.join(' / ')}</td></tr>`).join('')}</tbody></table>`}
function modulePage(model:any,module:any){const parts=model.parts.filter((p:any)=>p.moduleId===module.id);return `<section class="page"><h1>${esc(MODULE_TYPES[module.type]||module.type)}</h1><div class="meta">ID: ${esc(module.id)} · Ш×В×Г: <b>${module.width} × ${module.height} × ${module.depth} мм</b></div>${moduleSvg(model,module,140)}<h2>Деталировка для напила</h2>${parts.length?partsTable(parts):'<p>Для этого объекта нет мебельных деталей для напила.</p>'}<p class="warning">Перед производством проверить конструктив, кромление, сверловку, фурнитуру, вырезы и требования конкретного цеха.</p></section>`}
function reportHtml(project:any,model:any,moduleId?:string){const furniture=model.modules.filter((m:any)=>!['washer','dishwasher','oven','fridge'].includes(m.type));const chosen=moduleId?furniture.filter((m:any)=>m.id===moduleId):furniture;const cover=moduleId?'':`<section class="page"><h1>${esc(project.name||'Kitchen CAD')}</h1><div class="meta">Комната ${project.room.width} × ${project.room.depth} × ${project.room.height} мм · ${model.modules.length} объектов · ${model.parts.length} деталей</div>${overviewSvg(project,model)}<h2>Предупреждения</h2>${(model.warnings||[]).slice(0,12).map((w:string)=>`<div class="warning">${esc(w)}</div>`).join('')||'<p>Нет предупреждений.</p>'}<p>Далее каждый мебельный модуль идёт отдельной страницей, поэтому техника и соседние шкафы не перекрывают деталировку.</p></section>`;return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Kitchen CAD — печать</title><style>@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{margin:0;font:12px Arial,sans-serif;color:#16252b;background:#ddd}.page{width:100%;min-height:185mm;background:#fff;padding:5mm;page-break-after:always}.page:last-child{page-break-after:auto}h1{margin:0 0 4mm;font-size:22px}h2{font-size:15px;margin:4mm 0 2mm}.meta{margin-bottom:3mm;color:#51636a}.drawing{width:100%;height:100mm;border:1px solid #ccd5d7;border-radius:4px}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #cbd4d7;padding:3px;text-align:left}th{background:#eef2f3}.warning{border-left:3px solid #d79743;padding:4px 6px;margin:3px 0;background:#fff8ec}@media print{body{background:#fff}.page{padding:0}}</style></head><body>${cover}${chosen.map((m:any)=>modulePage(model,m)).join('')}<script>setTimeout(()=>window.print(),350)<\/script></body></html>`}
export function printReport(project:any,model:any,moduleId?:string){const w=window.open('','_blank');if(!w){alert('Браузер заблокировал окно печати. Разрешите всплывающие окна для этого сайта.');return}w.document.open();w.document.write(reportHtml(project,model,moduleId));w.document.close()}

export function downloadPng(project:any,model:any,moduleId?:string){const svg=moduleId?moduleSvg(model,model.modules.find((m:any)=>m.id===moduleId),140):overviewSvg(project,model);const source=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(source),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1840;c.height=940;const g=c.getContext('2d')!;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(b=>b&&blobDownload(b,moduleId?'module-drawing.png':'kitchen-overview.png'),'image/png')};img.src=url}
