import { cutListCSV } from '../../src/io/cut-list.js';
import { centimetres, workshopCardPages, workshopCutListCSV, workshopGroupedRows, workshopSheets } from '../../src/io/workshop-list.js';
import { MODULE_TYPES,SUBSTRATES,DECORS,MATERIAL_PRODUCTS,isDisplayOnlyType,materialProductLabel,decorLabel } from '../../src/catalog/materials.js';
import { explodedCentre } from '../domain/view-math.js';
import { estimateProjectCost } from '../../src/core/cost.js';
import { auditProductionReadiness } from '../../src/core/production-audit.js';

const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const safe=(s:string)=>s.replace(/[^a-z0-9а-яё._-]+/gi,'-').replace(/^-+|-+$/g,'')||'kitchen-cad';
const blobDownload=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),15000)};
export const downloadJson=(p:any)=>blobDownload(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),`${safe(p.name||'kitchen')}.json`);
export const downloadCsv=(m:any,id?:string,options:{draft?:boolean;blockers?:number}={})=>{const parts=id?m.parts.filter((p:any)=>p.moduleId===id):m.parts,raw=cutListCSV(parts),draft=options.draft===true,notice=`ЧЕРНОВИК — НЕ ПЕРЕДАВАТЬ В РАСПИЛ; блокирующих проверок: ${Number(options.blockers)||0}\r\n`,content=draft?raw.replace(/^\uFEFF/,`\uFEFF${notice}`):raw,name=`${draft?'DRAFT-NOT-FOR-CUTTING-':''}${id?'module':'project'}-cut-list.csv`;blobDownload(new Blob([content],{type:'text/csv;charset=utf-8'}),name)};
export const downloadWorkshopCsv=(project:any,model:any,options:{draft?:boolean}={})=>{const cost=estimateProjectCost(project,model),content=workshopCutListCSV(model,cost,options);blobDownload(new Blob([content],{type:'text/csv;charset=utf-8'}),`${options.draft?'DRAFT-NOT-FOR-CUTTING-':''}workshop-cut-list-cm.csv`)};

const isAr=(p:any)=>p.ui?.language==='ar';const isEn=(p:any)=>p.ui?.language!=='ru';const langCode=(p:any)=>isAr(p)?'ar':p.ui?.language==='en'?'en':'ru';const L=(p:any,ru:string,en:string,ar:string)=>isAr(p)?ar:p.ui?.language==='en'?en:ru;
const enNames:any={base:'Base cabinet',drawer:'Drawer cabinet',sink:'Sink cabinet',cornerBase:'Base corner cabinet',cornerBaseBlind:'Blind base corner cabinet',cornerBaseDiagonal:'Diagonal base corner cabinet',cornerBaseL:'L-shaped base corner cabinet',wall:'Wall cabinet',wallMicrowaveCombo:'Over-hood cabinet with microwave niche',cornerWall:'Wall corner cabinet',cornerWallBlind:'Blind wall corner cabinet',cornerWallDiagonal:'Diagonal wall corner cabinet',cornerWallL:'L-shaped wall corner cabinet',tall:'Tall cabinet',tallOven:'Oven tall cabinet'};
const arNames:any={base:'خزانة سفلية',drawer:'خزانة أدراج',sink:'خزانة حوض',cornerBase:'خزانة زاوية سفلية',cornerBaseBlind:'خزانة زاوية سفلية عمياء',cornerBaseDiagonal:'خزانة زاوية سفلية قطرية',cornerBaseL:'خزانة زاوية سفلية بشكل L',wall:'خزانة علوية',wallMicrowaveCombo:'خزانة فوق الشفاط مع حيز ميكروويف',cornerWall:'خزانة زاوية علوية',cornerWallBlind:'خزانة زاوية علوية عمياء',cornerWallDiagonal:'خزانة زاوية علوية قطرية',cornerWallL:'خزانة زاوية علوية بشكل L',tall:'خزانة طويلة',tallOven:'خزانة فرن طويلة'};
const moduleName=(type:string,project:any)=>langCode(project)==='ar'?(arNames[type]||type):langCode(project)==='en'?(enNames[type]||type):((MODULE_TYPES as any)[type]||type);
const mm=(project:any)=>L(project,'мм','mm','مم');
const pieces=(project:any)=>L(project,'шт.','pcs','قطعة');
function partName(project:any,p:any){
 const source=String(p?.name||p?.id||'');
 if(langCode(project)==='ru')return source;
 const exact:any={
  'Боковина левая':['Left side panel','الجانب الأيسر'],'Боковина правая':['Right side panel','الجانب الأيمن'],
  'Несущая боковина ниши левая':['Left load-bearing niche side','جانب الحيز الحامل الأيسر'],'Несущая боковина ниши правая':['Right load-bearing niche side','جانب الحيز الحامل الأيمن'],
  'Дно между боковинами':['Bottom between side panels','قاعدة بين الجانبين'],'Дно под боковинами':['Bottom under side panels','قاعدة أسفل الجانبين'],'Дно глухой секции':['Blind-section bottom','قاعدة القسم المغلق'],
  'Крышка сверху боковин':['Top over side panels','غطاء علوي فوق الجانبين'],'Верх между боковинами':['Top between side panels','غطاء علوي بين الجانبين'],
  'Задняя стенка накладная':['Overlay back panel','ظهر خارجي'],'Задняя стенка вкладная':['Inset back panel','ظهر داخلي'],
  'Передняя верхняя планка':['Front upper rail','عارضة علوية أمامية'],'Передняя вертикальная планка под вырез':['Front vertical rail below cut-out','عارضة أمامية رأسية أسفل الفتحة'],'Задняя верхняя планка':['Rear upper rail','عارضة علوية خلفية'],
  'Передняя верхняя планка ниши (горизонтальная)':['Front niche rail (horizontal)','عارضة الحيز الأمامية (أفقية)'],'Задняя верхняя планка ниши':['Rear niche rail','عارضة الحيز الخلفية'],
  'Съёмная декоративная планка над техникой':['Removable decorative filler above appliance','حشوة زخرفية قابلة للفك فوق الجهاز'],
  'Боковина верхнего шкафа левая':['Upper cabinet left side','جانب الخزانة العلوية الأيسر'],'Боковина верхнего шкафа правая':['Upper cabinet right side','جانب الخزانة العلوية الأيمن'],
  'Дно верхнего шкафа':['Upper cabinet bottom','قاعدة الخزانة العلوية'],'Крышка верхнего шкафа':['Upper cabinet top','غطاء الخزانة العلوية'],'Монтажная планка верхнего шкафа':['Upper cabinet mounting rail','عارضة تثبيت الخزانة العلوية'],
  'Боковина шкафа с нишей СВЧ левая':['Microwave cabinet left side','جانب خزانة الميكروويف الأيسر'],'Боковина шкафа с нишей СВЧ правая':['Microwave cabinet right side','جانب خزانة الميكروويف الأيمن'],
  'Нижняя боковина ниши СВЧ левая':['Microwave niche lower left side','جانب حيز الميكروويف السفلي الأيسر'],'Нижняя боковина ниши СВЧ правая':['Microwave niche lower right side','جانب حيز الميكروويف السفلي الأيمن'],
  'Верхняя боковина шкафа СВЧ левая':['Microwave cabinet upper left side','جانب خزانة الميكروويف العلوي الأيسر'],'Верхняя боковина шкафа СВЧ правая':['Microwave cabinet upper right side','جانب خزانة الميكروويف العلوي الأيمن'],
  'Нижняя полка ниши СВЧ':['Microwave niche bottom shelf','رف قاعدة حيز الميكروويف'],'Разделительная полка над СВЧ':['Shelf above microwave','رف فوق الميكروويف'],'Крышка шкафа с нишей СВЧ':['Microwave cabinet top','غطاء خزانة الميكروويف'],'Монтажная планка шкафа с нишей СВЧ':['Microwave cabinet mounting rail','عارضة تثبيت خزانة الميكروويف'],
  'Фасад верхнего шкафа':['Upper cabinet front','واجهة الخزانة العلوية'],'Полка для микроволновки':['Microwave shelf','رف الميكروويف'],
  'Цоколь':['Plinth','وزرة سفلية'],'Цоколь глухой секции':['Blind-section plinth','وزرة القسم المغلق'],
  'Глухая панель корпуса':['Blind cabinet panel','لوح الخزانة المغلق'],'Монтажная перегородка петель':['Hinge mounting partition','فاصل تثبيت المفصلات'],
  'Левый угловой добор фасада':['Left corner front filler','حشوة واجهة الزاوية اليسرى'],'Правый угловой добор фасада':['Right corner front filler','حشوة واجهة الزاوية اليمنى'],
  'Левое продолжение цоколя в угол':['Left plinth return into corner','امتداد الوزرة اليسرى داخل الزاوية'],'Правое продолжение цоколя в угол':['Right plinth return into corner','امتداد الوزرة اليمنى داخل الزاوية'],
  'Левая опорная стойка углового добора':['Left corner-filler support post','دعامة حشوة الزاوية اليسرى'],'Правая опорная стойка углового добора':['Right corner-filler support post','دعامة حشوة الزاوية اليمنى']
 };
 const translated=exact[source];if(translated)return translated[langCode(project)==='ar'?1:0];
 const numbered:[RegExp,string,string][]=[
  [/^Полка глухой секции (\d+)$/,'Blind-section shelf $1','رف القسم المغلق $1'],[/^Полка (\d+)$/,'Shelf $1','رف $1'],
  [/^Фасад ящика (\d+)$/,'Drawer front $1','واجهة الدرج $1'],[/^Диагональный фасад (\d+)$/,'Diagonal front $1','واجهة قطرية $1'],[/^L-фасад (\d+)$/,'L-shaped front $1','واجهة بشكل L $1'],[/^Фасад (\d+)$/,'Front $1','واجهة $1']
 ];
 for(const [pattern,en,ar] of numbered)if(pattern.test(source))return source.replace(pattern,langCode(project)==='ar'?ar:en);
 return source;
}
const svgOpen=(w:number,h:number)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" class="drawing"><rect width="100%" height="100%" fill="#fff"/>`;
const txt=(x:number,y:number,s:string,anchor='middle',size=11,weight=700)=>`<text x="${x}" y="${y}" text-anchor="${anchor}" font-size="${size}" font-family="Arial,sans-serif" fill="#26333a" font-weight="${weight}">${esc(s)}</text>`;
function dim(x1:number,y1:number,x2:number,y2:number,label:string){const dx=x2-x1,dy=y2-y1,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,mx=(x1+x2)/2,my=(y1+y2)/2,t=5;return `<g stroke="#6150b8" fill="none"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/><line x1="${x1-nx*t}" y1="${y1-ny*t}" x2="${x1+nx*t}" y2="${y1+ny*t}"/><line x1="${x2-nx*t}" y1="${y2-ny*t}" x2="${x2+nx*t}" y2="${y2+ny*t}"/></g><rect x="${mx-30}" y="${my-9}" width="60" height="17" rx="4" fill="#fff" stroke="#d5d0ed"/>${txt(mx,my+3,label)}`}
const iso=(x:number,y:number,z:number):[number,number]=>[(x-z)*.78,(x+z)*.28-y*.92];
function box(cx:number,cy:number,cz:number,sx:number,sy:number,sz:number,scale:number,ox:number,oy:number){const pts=[[cx-sx/2,cy-sy/2,cz-sz/2],[cx+sx/2,cy-sy/2,cz-sz/2],[cx+sx/2,cy+sy/2,cz-sz/2],[cx-sx/2,cy+sy/2,cz-sz/2],[cx-sx/2,cy-sy/2,cz+sz/2],[cx+sx/2,cy-sy/2,cz+sz/2],[cx+sx/2,cy+sy/2,cz+sz/2],[cx-sx/2,cy+sy/2,cz+sz/2]].map(([x,y,z])=>{const[u,v]=iso(x,y,z);return[ox+u*scale,oy+v*scale]});const p=(ids:number[])=>ids.map(i=>pts[i].join(',')).join(' ');return{pts,top:p([3,2,6,7]),front:p([4,5,6,7]),side:p([1,5,6,2])}}
function axisFor(size:number[],value:number,used:Set<number>){let best=0,d=Infinity;size.forEach((s,i)=>{if(!used.has(i)&&Math.abs(s-value)<d){best=i;d=Math.abs(s-value)}});used.add(best);return best}

function overviewSvg(project:any,model:any){const W=1120,H=620,pad=70,mods=model.modules||[],pts=mods.flatMap((m:any)=>{const a=[] as [number,number][];for(const x of[0,m.width])for(const y of[0,m.height])for(const z of[0,m.depth])a.push(iso(m.x+x,m.y+y,m.z+z));return a}),minU=Math.min(...pts.map(p=>p[0]),0),maxU=Math.max(...pts.map(p=>p[0]),1),minV=Math.min(...pts.map(p=>p[1]),0),maxV=Math.max(...pts.map(p=>p[1]),1),s=Math.min((W-2*pad)/Math.max(1,maxU-minU),(H-2*pad)/Math.max(1,maxV-minV)),ox=pad-minU*s,oy=pad-minV*s;let body='';for(const m of mods){const q=box(m.x+m.width/2,m.y+m.height/2,m.z+m.depth/2,m.width,m.height,m.depth,s,ox,oy),fill=isDisplayOnlyType(m.type)?'#dce3e6':'#eee9df';body+=`<polygon points="${q.front}" fill="${fill}" stroke="#607177"/><polygon points="${q.side}" fill="#d8d4ca" stroke="#607177"/><polygon points="${q.top}" fill="#faf8f2" stroke="#607177"/>`}return `${svgOpen(W,H)}${txt(45,30,L(project,'Общий вид проекта','Project overview','نظرة عامة على المشروع'),'start',20,800)}${body}</svg>`}
function orthographicSvg(project:any,model:any,module:any,view:'front'|'top'|'side'){const parts=model.parts.filter((p:any)=>p.moduleId===module.id),W=1120,H=620,pad=95;const cfg=view==='front'?{a:0,b:1,A:module.width,B:module.height,title:L(project,'Фронт','Front','أمامي')}:view==='top'?{a:0,b:2,A:module.width,B:module.depth,title:L(project,'Сверху','Top','علوي')}:{a:2,b:1,A:module.depth,B:module.height,title:L(project,'Сбоку','Side','جانبي')};const s=Math.min((W-2*pad)/Math.max(1,cfg.A),(H-2*pad)/Math.max(1,cfg.B));let body='';for(const p of parts){const c=p.center,size=p.size,originA=cfg.a===0?module.x:cfg.a===2?module.z:module.y,originB=cfg.b===0?module.x:cfg.b===2?module.z:module.y,x=pad+(c[cfg.a]-size[cfg.a]/2-originA)*s,y=H-pad-(c[cfg.b]+size[cfg.b]/2-originB)*s,w=Math.max(2,size[cfg.a]*s),h=Math.max(2,size[cfg.b]*s);body+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${p.role==='front'?'#dcebd7':'#f0ede5'}" stroke="#607177"/>`}const x0=pad,y0=H-pad;body+=dim(x0,y0+24,x0+cfg.A*s,y0+24,`${cfg.A} ${mm(project)}`);body+=dim(x0-24,y0,x0-24,y0-cfg.B*s,`${cfg.B} ${mm(project)}`);return `${svgOpen(W,H)}${txt(45,30,`${moduleName(module.type,project)} — ${cfg.title}`,'start',20,800)}${txt(45,52,`${L(project,'Ш×В×Г','W×H×D','ع×ا×ع')}: ${module.width} × ${module.height} × ${module.depth} ${mm(project)}`,'start',12,500)}${body}</svg>`}
function explodedSvg(project:any,model:any,module:any){const explode=Math.max(0,Math.min(500,Number(project.ui?.explode)||0)),parts=model.parts.filter((p:any)=>p.moduleId===module.id).map((p:any)=>({...p,drawCenter:explodedCentre(p,module,explode)})),W=1120,H=620,MAX=500,ref=[] as [number,number][];for(const x of[-MAX,module.width+MAX])for(const y of[-MAX,module.height+MAX])for(const z of[-MAX,module.depth+MAX])ref.push(iso(module.x+x,module.y+y,module.z+z));const minU=Math.min(...ref.map(p=>p[0])),maxU=Math.max(...ref.map(p=>p[0])),minV=Math.min(...ref.map(p=>p[1])),maxV=Math.max(...ref.map(p=>p[1])),s=Math.min(780/Math.max(1,maxU-minU),500/Math.max(1,maxV-minV)),ox=70-minU*s,oy=85-minV*s,mc=[module.x+module.width/2,module.y+module.height/2,module.z+module.depth/2];let body='';for(const p of parts){const q=box(p.drawCenter[0],p.drawCenter[1],p.drawCenter[2],p.size[0],p.size[1],p.size[2],s,ox,oy),fill=p.role==='front'?'#dcebd7':'#f0ede5';body+=`<polygon points="${q.front}" fill="${fill}" stroke="#607177"/><polygon points="${q.side}" fill="#dad7cf" stroke="#607177"/><polygon points="${q.top}" fill="#faf8f2" stroke="#607177"/>`;const used=new Set<number>(),axes:[[number,number],[number,number]]=[[axisFor(p.size,p.u,used),p.u],[axisFor(p.size,p.v,used),p.v]];for(let k=0;k<2;k++){const [axis,val]=axes[k];let a=q.pts[4],b=q.pts[5];if(axis===1){a=q.pts[5];b=q.pts[6]}else if(axis===2){a=q.pts[0];b=q.pts[4]}const sign=((p.drawCenter[(axis+1)%3]-mc[(axis+1)%3])>=0?1:-1),off=(k?16:9)*sign;body+=dim(a[0],a[1]+off,b[0],b[1]+off,`${Math.round(val)}`)}}return `${svgOpen(W,H)}${txt(45,30,`${moduleName(module.type,project)} — ${L(project,'Разобранный 3D','Exploded 3D','عرض ثلاثي الأبعاد مفكك')}`,'start',20,800)}${txt(45,52,`${L(project,'Разнос','Explode','التفكيك')}: ${explode} ${mm(project)}`,'start',12,500)}${body}</svg>`}
function productLabel(project:any,p:any){const product=MATERIAL_PRODUCTS[p.materialProductId];if(product)return materialProductLabel(product,langCode(project));const map:any={ldsp:{ru:'ЛДСП',en:'Laminated chipboard',ar:'لوح خشب مضغوط مغلف'},mdf:{ru:'МДФ',en:'MDF',ar:'MDF'},blockboard:{ru:'Столярная плита / Counter',en:'Blockboard / Counter',ar:'كونتر'},plywood:{ru:'Фанера',en:'Plywood',ar:'أبلكاش'}};const lang=langCode(project);return map[p.substrate]?.[lang]||SUBSTRATES[p.substrate]?.name||p.substrate}
function partsTable(project:any,parts:any[]){return `<table><thead><tr><th>#</th><th>ID</th><th>${L(project,'Деталь','Part','القطعة')}</th><th>${L(project,'Материал','Material','الخامة')}</th><th>${L(project,'Готовый размер','Finished','المقاس النهائي')}</th><th>${L(project,'Заготовка','Blank','مقاس القص')}</th><th>${L(project,'Кромка','Edge','الحافة')}</th></tr></thead><tbody>${parts.map((p:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(p.id)}</td><td>${esc(partName(project,p))}</td><td>${esc(productLabel(project,p))} / ${esc(decorLabel(DECORS[p.decor],langCode(project))||p.decor)}</td><td>${p.u} × ${p.v} × ${p.thickness} ${mm(project)}</td><td>${p.blankU} × ${p.blankV} × ${p.thickness} ${mm(project)}</td><td>${esc(p.edgeType||'')} ${p.edges.join(' / ')}</td></tr>`).join('')}</tbody></table>`}
function edgeLabel(project:any,value:number,type:string){return value>0?`${type||"ABS"} ${value} ${mm(project)}`:L(project,'без кромки','no edge','بدون حافة')}
function edgeSide(project:any,p:any,index:number,side:[string,string,string],axis:string){const value=(p.edges||[0,0,0,0])[index]||0,label=langCode(project)==='ar'?side[2]:langCode(project)==='en'?side[1]:side[0];return {on:value>0,text:`${label} (${axis}): ${edgeLabel(project,value,p.edgeType)}`}}
function hingeDrilling(project:any,p:any){const d=p.hingeDrilling;if(!d||!p.hingeSide)return{marks:'',meta:''};const positions=d.positionsFromTop||[],side=p.hingeSide==='left'?'left':'right',marks=positions.map((value:number)=>`<i style="position:absolute;${side}:1mm;top:${Math.max(0,Math.min(100,value/Math.max(1,p.v)*100))}%;width:7mm;height:7mm;border:1.5px solid #6d54d9;border-radius:50%;transform:translateY(-50%);background:rgba(109,84,217,.12)"></i>`).join(''),meta=`<span>${L(project,'Сверление петель','Hinge drilling','تخريم المفصلات')}: <b>Ø${d.cupDiameter} × ${d.cupDepth} ${mm(project)}; ${d.cupCenterFromEdge} ${mm(project)} ${L(project,'до центра от кромки','centre from edge','من الحافة إلى المركز')}; ${L(project,'от верха','from top','من الأعلى')} ${positions.join(' / ')} ${mm(project)}</b></span>`;return{marks,meta}}
function partDiagramSvg(project:any,p:any,sides:any[]){const W=430,H=150,u=Math.max(1,Number(p.blankU)||Number(p.u)||1),v=Math.max(1,Number(p.blankV)||Number(p.v)||1),scale=Math.min(286/u,92/v),pw=Math.max(14,u*scale),ph=Math.max(10,v*scale),x=(W-pw)/2,y=(H-ph)/2-2,dx=7,dy=5,edge=(index:number,x1:number,y1:number,x2:number,y2:number)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${sides[index].on?'#6d54d9':'#9aa7ac'}" stroke-width="${sides[index].on?4:1}" ${sides[index].on?'':'stroke-dasharray="4 3"'}/>`,holes=p.hingeDrilling&&p.hingeSide?(p.hingeDrilling.positionsFromTop||[]).map((value:number)=>{const cy=y+Math.max(0,Math.min(1,value/Math.max(1,Number(p.v)||v)))*ph,cx=p.hingeSide==='left'?x+Math.min(11,pw*.08):x+pw-Math.min(11,pw*.08);return `<circle cx="${cx}" cy="${cy}" r="5" fill="none" stroke="#6d54d9" stroke-width="2"/><line x1="${cx-7}" y1="${cy}" x2="${cx+7}" y2="${cy}" stroke="#6d54d9"/><line x1="${cx}" y1="${cy-7}" x2="${cx}" y2="${cy+7}" stroke="#6d54d9"/>`}).join(''):'',directional=['wood','stone'].includes(p.appearance?.pattern),grain=directional?`<g stroke="#73858c" stroke-width="1.5" fill="none"><line x1="${x+pw*.28}" y1="${y+ph*.5}" x2="${x+pw*.72}" y2="${y+ph*.5}"/><path d="M ${x+pw*.68} ${y+ph*.44} L ${x+pw*.72} ${y+ph*.5} L ${x+pw*.68} ${y+ph*.56}"/></g>`:'';return `<svg viewBox="0 0 ${W} ${H}" class="partDrawing" role="img" aria-label="${esc(partName(project,p))}"><polygon points="${x},${y} ${x+dx},${y-dy} ${x+pw+dx},${y-dy} ${x+pw},${y}" fill="#faf8f2" stroke="#607177"/><polygon points="${x+pw},${y} ${x+pw+dx},${y-dy} ${x+pw+dx},${y+ph-dy} ${x+pw},${y+ph}" fill="#d9d6ce" stroke="#607177"/><rect x="${x}" y="${y}" width="${pw}" height="${ph}" fill="#f0ede5" stroke="#42545b" stroke-width="1.5"/>${edge(0,x,y,x,y+ph)}${edge(1,x+pw,y,x+pw,y+ph)}${edge(2,x,y,x+pw,y)}${edge(3,x,y+ph,x+pw,y+ph)}${holes}${grain}<g stroke="#6150b8" fill="none"><line x1="${x}" y1="${y+ph+16}" x2="${x+pw}" y2="${y+ph+16}"/><line x1="${x}" y1="${y+ph+11}" x2="${x}" y2="${y+ph+21}"/><line x1="${x+pw}" y1="${y+ph+11}" x2="${x+pw}" y2="${y+ph+21}"/><line x1="${x-18}" y1="${y}" x2="${x-18}" y2="${y+ph}"/><line x1="${x-23}" y1="${y}" x2="${x-13}" y2="${y}"/><line x1="${x-23}" y1="${y+ph}" x2="${x-13}" y2="${y+ph}"/></g>${txt(x+pw/2,y+ph+30,`${u} ${mm(project)}`,'middle',11,700)}<text x="${x-31}" y="${y+ph/2}" text-anchor="middle" font-size="11" font-family="Arial,sans-serif" fill="#26333a" font-weight="700" transform="rotate(-90 ${x-31} ${y+ph/2})">${esc(`${v} ${mm(project)}`)}</text>${txt(x+pw/2,y+ph/2+4,`${p.thickness} ${mm(project)}`,'middle',10,700)}</svg>`}
function cutCard(project:any,p:any,index:number,total:number){const dir=isAr(project)?'rtl':'ltr',sides=[edgeSide(project,p,0,['Левая','Left','يسار'],'U−'),edgeSide(project,p,1,['Правая','Right','يمين'],'U+'),edgeSide(project,p,2,['Верхняя','Top','أعلى'],'V−'),edgeSide(project,p,3,['Нижняя','Bottom','أسفل'],'V+')],drill=hingeDrilling(project,p);return `<article class="cutCard" dir="${dir}"><div class="cutHead"><b>${esc(p.id)} · ${esc(partName(project,p))}</b><span>${L(project,"Деталь","Part","قطعة")} ${index+1} / ${total}</span></div><div class="cutSize">${L(project,'РАСПИЛ / заготовка','SAW CUT / blank','مقاس القص')}: ${p.blankU} × ${p.blankV} × ${p.thickness} ${mm(project)}</div><div class="partDiagram">${partDiagramSvg(project,p,sides)}<div class="edgeLegend">${sides.map(side=>`<span class="${side.on?'edgeOn':'edgeOff'}">${esc(side.text)}</span>`).join('')}</div></div><div class="cutMeta"><span>${L(project,"Материал","Material","الخامة")}: <b>${esc(productLabel(project,p))}</b></span><span>${L(project,"Декор","Decor","اللون/الديكور")}: <b>${esc(decorLabel(DECORS[p.decor],langCode(project))||p.decor)}</b></span><span>${L(project,"Готовый размер после кромки","Finished after edging","المقاس النهائي بعد الحافة")}: <b>${p.u} × ${p.v} × ${p.thickness} ${mm(project)}</b></span><span>${L(project,"Количество","Qty","الكمية")}: <b>1</b></span>${p.role==='front'&&p.hingeSide?`<span>${L(project,'Петли','Hinges','المفصلات')}: <b>${p.hingeSide==='left'?L(project,'слева','left','يسار'):L(project,'справа','right','يمين')} · ${p.hingeCount||2} ${pieces(project)}</b></span>${drill.meta}`:''}</div></article>`}
function cutCardsSheets(project:any,module:any,parts:any[]){const pages:string[]=[];for(let i=0;i<parts.length;i+=4){const chunk=parts.slice(i,i+4),title=`${moduleName(module.type,project)} — ${L(project,"Карты деталей для напила","Cut cards","بطاقات القص")}`,meta=`${L(project,"Габарит модуля","Module size","مقاس الوحدة")}: <b>${module.width} × ${module.height} × ${module.depth} ${mm(project)}</b> · ${L(project,"Всего деталей","Total parts","إجمالي القطع")}: <b>${parts.length}</b>`;pages.push(page(title,meta,`<div class="cutCards">${chunk.map((p:any,j:number)=>cutCard(project,p,i+j,parts.length)).join("")} </div>`,'cutCardsPage'))}return pages.join('')}
const page=(title:string,meta:string,body:string,cls='')=>`<section class="page ${cls}"><h1>${esc(title)}</h1><div class="meta">${meta}</div>${body}</section>`;
function orthoSheet(project:any,model:any,module:any){const name=moduleName(module.type,project),meta=`${L(project,'Ш×В×Г','W×H×D','ع×ا×ع')}: <b>${module.width} × ${module.height} × ${module.depth} ${mm(project)}</b>`;return page(`${name} — ${L(project,'Размеры','Dimensions','الأبعاد')}`,meta,`<div class="orthoGrid"><div>${orthographicSvg(project,model,module,'front')}</div><div>${orthographicSvg(project,model,module,'top')}</div><div>${orthographicSvg(project,model,module,'side')}</div></div>`,'orthoPage')}
function assemblySheet(project:any,model:any,module:any,scenePng?:string|null){const name=moduleName(module.type,project),parts=model.parts.filter((p:any)=>p.moduleId===module.id),explode=Math.max(0,Math.min(500,Number(project.ui?.explode)||0)),meta=`${L(project,'Разнос','Explode','التفكيك')}: <b>${explode} ${mm(project)}</b>`;const visual=scenePng?`<div class="sceneShot"><img src="${scenePng}" alt="3D"/></div>`:`<div class="fallback3d">${explodedSvg(project,model,module)}</div>`;return page(`${name} — ${L(project,'Сборка + напил','Assembly + cut list','التجميع + قائمة القص')}`,meta,`<div class="assemblyGrid"><div class="visualCol">${visual}</div><div class="tableCol"><h2>${L(project,'Напил','Cut list','قائمة القص')}</h2>${partsTable(project,parts)}<p class="warning">${L(project,'3D-снимок использует текущий ракурс и разнос сцены. Перед производством проверить сверловку, фурнитуру, вырезы и припуски конкретного цеха.','The 3D snapshot uses the current camera and exploded-view state. Verify drilling, hardware, cut-outs and workshop tolerances before production.','تستخدم لقطة 3D زاوية الكاميرا وحالة التفكيك الحالية. تحقق من التخريم والإكسسوارات والفتحات وسماحات الورشة قبل التصنيع.')}</p></div></div>`,'assemblyPage')}
function countertopJointSummary(project:any,model:any){const j=model.countertopJoints||[];if(!j.length)return'';return page(L(project,'Стыки столешницы','Countertop joints','وصلات سطح العمل'),L(project,'Всего','Total','الإجمالي')+': <b>'+j.length+'</b>',`<table><thead><tr><th>#</th><th>${L(project,'Тип','Type','النوع')}</th><th>${L(project,'Зазор','Gap','الفاصل')}</th><th>${L(project,'Сегменты','Segments','القطاعات')}</th></tr></thead><tbody>${j.map((x:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(x.type)}</td><td>${x.gap} mm</td><td>${esc(x.segmentAId)} + ${esc(x.segmentBId)}</td></tr>`).join('')}</tbody></table>`)}
function countertopSummary(project:any,model:any){const s=model.countertopSegments||[];if(!s.length)return'';return page(L(project,'Столешница — сегменты','Countertop — segments','سطح العمل — القطاعات'),L(project,'Всего','Total','الإجمالي')+': <b>'+s.length+'</b>',`<table><thead><tr><th>#</th><th>${L(project,'Стена','Wall','الجدار')}</th><th>${L(project,'Длина','Length','الطول')}</th><th>${L(project,'Глубина','Depth','العمق')}</th><th>${L(project,'Толщина','Thickness','السماكة')}</th></tr></thead><tbody>${s.map((x:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(x.wall)}</td><td>${x.length} mm</td><td>${x.depth} mm</td><td>${x.thickness} mm</td></tr>`).join('')}</tbody></table>`)}
function hardwareTable(project:any,cost:any){const lang=langCode(project),rows=cost.hardwareBill||[];if(!rows.length)return'';return `<h2>${L(project,'Фурнитура и крепёж','Hardware and fasteners','الإكسسوارات والمثبتات')}</h2><table><thead><tr><th>#</th><th>${L(project,'Позиция','Item','الصنف')}</th><th>${L(project,'Количество','Quantity','الكمية')}</th><th>${L(project,'Цена','Unit price','سعر الوحدة')}</th><th>${L(project,'Сумма','Cost','التكلفة')}</th></tr></thead><tbody>${rows.map((row:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(row.names?.[lang]||row.name)}</td><td>${row.quantity} ${esc(row.units?.[lang]||row.unit)}${row.optionalQuantity?` + ${L(project,'опция','optional','اختياري')} ${row.optionalQuantity}`:''}</td><td>${Math.round(row.unitPrice)} EGP</td><td>${Math.round(row.cost)} EGP${row.optionalCost?` (+${Math.round(row.optionalCost)} EGP)` :''}</td></tr>`).join('')}</tbody></table><p class="warning">${L(project,'Цены — ориентир онлайн-розницы Египта на 19.09.2026 и редактируются в смете. Опциональные ручки не включены в итог.','Prices are editable Egypt online-retail references checked 19 Sep 2026. Optional handles are excluded from the total.','الأسعار تقديرية وقابلة للتعديل لمتاجر مصر بتاريخ 19-09-2026. المقابض الاختيارية غير داخلة في الإجمالي.')}</p>`}
function productionSummary(project:any,model:any){const cost=estimateProjectCost(project,model),audit=auditProductionReadiness(project,model,cost),status=audit.ready?L(project,'Автоматические проверки пройдены','Automated checks passed','تم اجتياز الفحوصات'):L(project,'НЕ ГОТОВО К ПРОИЗВОДСТВУ','NOT PRODUCTION-READY','غير جاهز للتصنيع'),rows=audit.findings.map((item:any,i:number)=>`<tr><td>${i+1}</td><td>${item.severity==='blocker'?L(project,'Блокер','Blocker','مانع'):L(project,'Предупреждение','Warning','تحذير')}</td><td>${esc(item.message)}</td></tr>`).join('');return page(L(project,'Смета проекта и готовность','Project cost & production readiness','تكلفة المشروع وجاهزية التصنيع'),`<b>${status}</b> · ${L(project,'Блокеров','Blockers','موانع')}: ${audit.blockers.length} · ${L(project,'Предупреждений','Warnings','تحذيرات')}: ${audit.warnings.length}`,`<div class="costSummary"><p><b>${L(project,'К закупке','Purchase total','إجمالي الشراء')}: ${Math.round(cost.procurementTotal).toLocaleString()} ${esc(cost.settings.currency)}</b></p><p>${L(project,'Израсходованный материал и работы','Consumed material and work','الخامات والأعمال المستهلكة')}: ${Math.round(cost.consumedTotal).toLocaleString()} ${esc(cost.settings.currency)}</p><p>${L(project,'Фурнитура и крепёж','Hardware and fasteners','الإكسسوارات والمثبتات')}: ${Math.round(cost.hardware).toLocaleString()} EGP</p><p>${L(project,'Целые листы','Whole sheets','ألواح كاملة')}: ${cost.sheetCount}; ${L(project,'кромка','edge','حواف')}: ${cost.edge.meters.toFixed(1)} m</p></div>${hardwareTable(project,cost)}${rows?`<h2>${L(project,'Проверки','Checks','الفحوصات')}</h2><table><thead><tr><th>#</th><th>${L(project,'Статус','Status','الحالة')}</th><th>${L(project,'Проверка','Check','الفحص')}</th></tr></thead><tbody>${rows}</tbody></table>`:`<p>${L(project,'Блокирующих замечаний нет. Требования цеха всё равно подтвердить перед производством.','No blocking findings. Confirm workshop requirements before production.','لا توجد ملاحظات مانعة. أكد متطلبات الورشة قبل التصنيع.')}</p>`}`)}
function stockSheetSvg(project:any,sheet:any){const labels=(sheet.placements||[]).map((item:any)=>{const cx=item.x+item.width/2,cy=item.y+item.height/2,showSize=item.width>210&&item.height>115;return `<g><rect x="${item.x}" y="${item.y}" width="${item.width}" height="${item.height}" fill="#d9edf0" stroke="#187f8d" stroke-width="5"/><text x="${cx}" y="${cy-(showSize?25:0)}" text-anchor="middle" dominant-baseline="middle" font-size="${Math.min(54,Math.max(30,item.width/9))}" font-family="Arial,sans-serif" font-weight="800" fill="#17343b">#${item.sequence} ${esc(item.id)}</text>${showSize?`<text x="${cx}" y="${cy+34}" text-anchor="middle" dominant-baseline="middle" font-size="38" font-family="Arial,sans-serif" fill="#17343b">${item.width}×${item.height}</text>`:''}</g>`}).join('');return `<svg viewBox="0 0 ${sheet.width} ${sheet.height}" class="stockDrawing" role="img" aria-label="${esc(L(project,'Карта распила листа','Sheet cutting map','مخطط قص اللوح'))}"><rect width="${sheet.width}" height="${sheet.height}" fill="#f4f4f1" stroke="#42545b" stroke-width="8"/><rect x="${sheet.trim}" y="${sheet.trim}" width="${sheet.usableWidth}" height="${sheet.usableHeight}" fill="none" stroke="#8a969a" stroke-width="4" stroke-dasharray="18 12"/>${labels}</svg>`}
function stockLayoutSheets(project:any,model:any){const cost=estimateProjectCost(project,model),groups=[{role:L(project,'Корпус','Carcass','الهيكل'),batches:cost.body.batches},{role:L(project,'Фасад','Front','الواجهة'),batches:cost.front.batches},{role:L(project,'Задники','Backs','الظهور'),batches:cost.back.batches}],pages:string[]=[];for(const group of groups)for(const batch of group.batches||[])for(const sheet of batch.stockPlan?.sheets||[]){const title=`${L(project,'Карта листа','Sheet map','مخطط اللوح')} ${sheet.index} — ${group.role}`,meta=`${esc(batch.materialName)} · ${esc(decorLabel(DECORS[batch.decor],langCode(project))||batch.decor)} · ${sheet.width}×${sheet.height}×${batch.thickness} ${mm(project)} · ${L(project,'пропил','kerf','عرض القطع')} ${batch.stockPlan.kerf} ${mm(project)} · ${L(project,'обрезка края','edge trim','تشذيب الحافة')} ${batch.stockPlan.trim} ${mm(project)}`,rows=(sheet.placements||[]).map((item:any)=>`<tr><td>${item.sequence}</td><td><b>${esc(item.id)}</b></td><td>${esc(partName(project,item))}</td><td>${item.width}×${item.height}</td><td>X ${item.x}; Y ${item.y}</td><td>${item.rotated?'↻ ':''}${item.firstCut==='vertical'?'V→H':'H→V'}${item.grainLocked?' · ↕':''}</td></tr>`).join(''),note=L(project,'Координаты X/Y даны от левого верхнего угла исходного листа и уже включают обрезку края. Схема не допускает пересечений, учитывает пропил и построена гильотинными разрезами. Перед станком технолог цеха обязан подтвердить базирование, фактический пропил, порядок резов и направление декора.','X/Y coordinates start at the untrimmed sheet’s top-left corner and include the edge trim. The non-overlapping layout includes kerf and uses guillotine cuts. Before machining, the workshop technician must confirm datum, actual kerf, cut order and decor direction.','تبدأ إحداثيات X/Y من الزاوية العلوية اليسرى للوح الخام وتشمل تشذيب الحافة. المخطط بلا تداخل ويحسب عرض القطع ويستخدم قصات مستقيمة. يجب على فني الورشة تأكيد نقطة القياس وعرض القطع وترتيب القص واتجاه الديكور قبل التشغيل.');pages.push(page(title,meta,`<div class="stockGrid"><div>${stockSheetSvg(project,sheet)}</div><div><table class="stockTable"><thead><tr><th>#</th><th>ID</th><th>${L(project,'Деталь','Part','القطعة')}</th><th>${L(project,'Размер на листе','On-sheet size','المقاس على اللوح')}</th><th>X / Y</th><th>${L(project,'Порядок','Order','الترتيب')}</th></tr></thead><tbody>${rows}</tbody></table><p class="warning">${note}</p></div></div>`,'stockPage'))}return pages.join('')}

const workshopRole=(project:any,role:string)=>role==='body'?L(project,'Корпус','Carcass','الهيكل'):role==='front'?L(project,'Фасады','Fronts','الواجهات'):L(project,'Задники','Backs','الظهور');
function workshopMasterRow(project:any,row:any,index:number){
  const names=[...new Set(row.parts.map((part:any)=>partName(project,part)))],ids=row.parts.map((part:any)=>part.id).join(', '),edge=(side:number)=>Number(row.edges?.[side])>0?'<b>1</b>':'';
  return `<tr><td class="seq">${index}</td><td class="size">${centimetres(row.blankU)}</td><td class="size">${centimetres(row.blankV)}</td><td class="qty">${row.quantity}</td><td>${esc(decorLabel(DECORS[row.decor],langCode(project))||row.decor)}</td><td class="rotate">${row.rotationAllowed?'✓':'—'}</td><td>${esc(names.join(' / '))}<small>${esc(ids)} · ${L(project,'готово','finished','النهائي')} ${centimetres(row.u)} × ${centimetres(row.v)} cm</small></td>${[0,1,2,3].map(side=>`<td class="edge ${Number(row.edges?.[side])>0?'yes':'no'}">${edge(side)}</td>`).join('')}</tr>`;
}
export function workshopReportHtml(project:any,model:any,options:{draft?:boolean}={}){
  const cost=estimateProjectCost(project,model),{unplaced}=workshopSheets(model,cost),rows=workshopGroupedRows(model),sections=new Map<string,any[]>(),pages:string[]=[];
  for(const row of rows){const key=[row.role,row.materialProductId,row.decor,row.thickness].join('|');if(!sections.has(key))sections.set(key,[]);sections.get(key)!.push(row)}
  const header=`<thead><tr><th>#</th><th>${L(project,'Длина U, см','Length U, cm','الطول U سم')}</th><th>${L(project,'Ширина V, см','Width V, cm','العرض V سم')}</th><th>${L(project,'Кол-во','Qty','الكمية')}</th><th>${L(project,'Материал','Material','مواد')}</th><th>${L(project,'Поворот','Rotate','دوران')}</th><th>${L(project,'Деталь / ID','Part / ID','التسمية / ID')}</th><th>${L(project,'Левая','Left','اليسار')}</th><th>${L(project,'Правая','Right','اليمين')}</th><th>${L(project,'Верх','Top','أعلى')}</th><th>${L(project,'Низ','Bottom','الأسفل')}</th></tr></thead>`;
  for(const sectionRows of sections.values()){
    const first=sectionRows[0],product=MATERIAL_PRODUCTS[first.materialProductId],total=sectionRows.reduce((sum:number,row:any)=>sum+row.quantity,0),edgeValues=[...new Set(sectionRows.flatMap((row:any)=>row.edges).filter((value:number)=>value>0))];
    for(let start=0;start<sectionRows.length;start+=22){
      const chunk=sectionRows.slice(start,start+22),pageNo=Math.floor(start/22)+1,pageCount=Math.ceil(sectionRows.length/22),continuation=pageCount>1?` (${pageNo}/${pageCount})`:'';
      const title=`${workshopRole(project,first.role)}${continuation}`;
      const stock=product?`${centimetres(product.sheetWidth)} × ${centimetres(product.sheetHeight)} × ${centimetres(first.thickness)} cm`: `${centimetres(first.thickness)} cm`;
      const edgeLegend=edgeValues.length?edgeValues.map(value=>`${first.edgeType||'ABS'} ${value} mm`).join(' / '):L(project,'без кромки','no edging','بدون حافة');
      const meta=`${esc(productLabel(project,first.parts[0]))} · ${esc(decorLabel(DECORS[first.decor],langCode(project))||first.decor)} · ${stock} · ${total} ${pieces(project)}`;
      const startIndex=start+1;
      pages.push(`<section class="workshopPage"><h1>${esc(project.name||'Kitchen CAD')} — ${esc(title)}</h1><p class="sheetMeta">${meta}</p>${options.draft?`<p class="draft">${L(project,'ЧЕРНОВИК — СВЕРИТЬ ПЕРЕД РАСПИЛОМ','DRAFT — VERIFY BEFORE CUTTING','مسودة — تحقق قبل القص')}</p>`:''}<p class="key">${L(project,'Формат как у мастера: размеры U/V — заготовка ДО кромки, в сантиметрах; количество уже сгруппировано. В колонке кромки «1» означает обработать эту сторону.','Workshop format: U/V are blank sizes BEFORE edging in centimetres; identical parts are grouped by quantity. “1” in an edge column means edge that side.','تنسيق الورشة: أبعاد U/V قبل تلبيس الحافة بالسنتيمتر، والقطع المتطابقة مجمعة بالكمية. الرقم 1 يعني تلبيس هذا الجانب.')} ${L(project,'Кромка этой группы','Edge for this group','حافة هذه المجموعة')}: ${esc(edgeLegend)}.</p><table>${header}<tbody>${chunk.map((row:any,index:number)=>workshopMasterRow(project,row,startIndex+index)).join('')}</tbody></table><p class="foot">${L(project,'Сумма количества в этой группе','Total pieces in this group','إجمالي قطع هذه المجموعة')}: ${total}. ${L(project,'Размер «готово» указан мелким текстом для сверки со сценой. Перед резом мастер подтверждает лист, пропил и ориентацию; столешница, отверстия и сверление петель согласуются отдельно.','Finished size is shown in small text to cross-check the scene. Confirm sheet stock, kerf and orientation before cutting; countertop, cut-outs and hinge drilling are separate.','المقاس النهائي مكتوب بخط صغير للمطابقة مع المشهد. يجب تأكيد اللوح وعرض القطع والاتجاه قبل القص؛ السطح والفتحات وتخريم المفصلات منفصلة.')}</p></section>`);
    }
  }
  if(unplaced.length)pages.unshift(`<section class="workshopPage"><h1 class="draft">${L(project,'ЕСТЬ НЕРАЗМЕЩЁННЫЕ ДЕТАЛИ — НЕ ПИЛИТЬ','UNPLACED PARTS — DO NOT CUT','توجد قطع غير موزعة — لا تقص')}</h1></section>`);
  return `<!doctype html><html lang="${langCode(project)}" dir="${isAr(project)?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(L(project,'Ведомость для цеха · см','Workshop cut list · cm','قائمة القص · سم'))}</title><style>@page{size:A4 landscape;margin:8mm}*{box-sizing:border-box}body{margin:0;background:#eef1f2;color:#16262c;font:11px Arial,sans-serif}.workshopPage{width:100%;min-height:194mm;padding:5mm;background:white;break-after:page}.workshopPage:last-child{break-after:auto}h1{font-size:18px;margin:0 0 2mm}.sheetMeta{font-size:12px;font-weight:700;margin:0 0 2mm}.key{font-size:9px;line-height:1.3;padding:1.5mm 2mm;background:#edf5f6;border-left:3px solid #308b9a;margin:0 0 2mm}.draft{color:#b42222;font-size:14px;font-weight:800;margin:1mm 0}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9px}th,td{border:1px solid #74868d;padding:.8mm;vertical-align:middle;overflow-wrap:anywhere}th{background:#dce8eb;text-align:center;font-size:8px}th:nth-child(1){width:3%}th:nth-child(2),th:nth-child(3){width:9%}th:nth-child(4){width:5%}th:nth-child(5){width:10%}th:nth-child(6){width:6%}th:nth-child(7){width:32%}th:nth-child(n+8){width:6.5%}.seq,.qty,.size,.rotate{font-weight:700;text-align:center}.size{white-space:nowrap;font-size:10px}.edge{text-align:center;font-size:11px}.edge.yes{background:#e1f3e8}.edge.no{background:#fafafa}small{display:block;color:#4d646e;font-size:7px;margin-top:.4mm}.foot{margin-top:2mm;font-size:8px;line-height:1.3;border-top:1px solid #bbc8cd;padding-top:1.5mm}@media print{body{background:white}.workshopPage{padding:0;min-height:0}tr{break-inside:avoid}}</style></head><body>${pages.join('')}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`;
}
export function printWorkshopReport(project:any,model:any,options:{draft?:boolean}={}){const w=window.open('','_blank');if(!w){alert(L(project,'Браузер заблокировал окно печати.','Pop-up blocked.','تم حظر نافذة الطباعة.'));return}w.document.open();w.document.write(workshopReportHtml(project,model,options));w.document.close()}

function workshopSketchSvg(project:any,part:any){
  const W=420,H=156,u=Math.max(1,Number(part.u)||1),v=Math.max(1,Number(part.v)||1),scale=Math.min(278/u,92/v),w=Math.max(16,u*scale),h=Math.max(12,v*scale),x=(W-w)/2+12,y=(H-h)/2-6;
  const marked=(index:number,x1:number,y1:number,x2:number,y2:number)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${Number(part.edges?.[index])>0?'#312866':'#7d898e'}" stroke-width="${Number(part.edges?.[index])>0?5:1.5}" ${Number(part.edges?.[index])>0?'':'stroke-dasharray="4 3"'}/>`;
  return `<svg class="sketchDrawing" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(partName(project,part))}"><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#fff" stroke="#26343a" stroke-width="1"/>${marked(0,x,y,x,y+h)}${marked(1,x+w,y,x+w,y+h)}${marked(2,x,y,x+w,y)}${marked(3,x,y+h,x+w,y+h)}<line x1="${x}" y1="${y+h+13}" x2="${x+w}" y2="${y+h+13}" stroke="#26343a"/><line x1="${x}" y1="${y+h+8}" x2="${x}" y2="${y+h+18}" stroke="#26343a"/><line x1="${x+w}" y1="${y+h+8}" x2="${x+w}" y2="${y+h+18}" stroke="#26343a"/><line x1="${x-18}" y1="${y}" x2="${x-18}" y2="${y+h}" stroke="#26343a"/><line x1="${x-23}" y1="${y}" x2="${x-13}" y2="${y}" stroke="#26343a"/><line x1="${x-23}" y1="${y+h}" x2="${x-13}" y2="${y+h}" stroke="#26343a"/>${txt(x+w/2,y+h+28,`${centimetres(u)} cm`,'middle',13,800)}<text x="${x-30}" y="${y+h/2}" transform="rotate(-90 ${x-30} ${y+h/2})" text-anchor="middle" font-size="13" font-family="Arial,sans-serif" font-weight="800" fill="#26343a">${centimetres(v)} cm</text></svg>`;
}
function workshopSketchCard(project:any,part:any,placement:any){
  const english=partName({...project,ui:{...project.ui,language:'en'}},part),primary=partName(project,part),sides=[L(project,'слева','left','يسار'),L(project,'справа','right','يمين'),L(project,'сверху','top','أعلى'),L(project,'снизу','bottom','أسفل')],edges=sides.map((side,index)=>`${side}: ${Number(part.edges?.[index])>0?`${esc(part.edgeType||'ABS')} ${esc(part.edges[index])} mm`:'-'}`).join(' · ');
  return `<article class="sketchCard"><div class="sketchHead"><b>${placement?.sequence||'!'} · ${esc(part.id)}</b><span>1 ${pieces(project)}</span></div><div class="sketchName">${esc(primary)}${english!==primary?` <small>/ ${esc(english)}</small>`:''}</div><div class="sketchMaterial">${esc(productLabel(project,part))} · ${esc(decorLabel(DECORS[part.decor],langCode(project))||part.decor)}</div><div class="sketchCut">${L(project,'ГОТОВЫЙ РАЗМЕР / после кромки','FINISHED SIZE / after edging','المقاس النهائي بعد الحافة')}: <b>${centimetres(part.u)} × ${centimetres(part.v)} × ${centimetres(part.thickness)} cm</b></div>${workshopSketchSvg(project,part)}<div class="sketchEdges"><b>${L(project,'Кромка / тёмные стороны','Edge / dark sides','الحافة / الجوانب الداكنة')}:</b> ${edges}</div><div class="sketchFinished">${L(project,'Заготовка до кромки','Blank before edging','القطعة قبل الحافة')}: ${centimetres(part.blankU)} × ${centimetres(part.blankV)} cm</div></article>`;
}
export function workshopSketchReportHtml(project:any,model:any,options:{draft?:boolean}={}){
  const cost=estimateProjectCost(project,model),pages=workshopCardPages(model,cost,4),body=pages.map(({role,batch,sheet,rows,unplaced}:any,index:number)=>{
    const title=unplaced?L(project,'НЕ РАЗМЕЩЕНО НА ЛИСТЕ','UNPLACED PARTS','قطع غير موزعة'): `${workshopRole(project,role)} · ${L(project,'лист','sheet','لوح')} ${sheet.index}`;
    const meta=unplaced?'':`${esc(batch.materialName)} · ${esc(decorLabel(DECORS[batch.decor],langCode(project))||batch.decor)} · ${centimetres(sheet.width)} × ${centimetres(sheet.height)} cm`;
    const draftLabel=unplaced?L(project,'НЕ РАЗМЕЩЕНО — НЕ ПИЛИТЬ','UNPLACED — DO NOT CUT','غير موزعة — لا تقص'):L(project,'ЧЕРНОВИК — СВЕРИТЬ ПЕРЕД РАСПИЛОМ','DRAFT — VERIFY BEFORE CUTTING','مسودة — تحقق قبل القص');
    return `<section class="sketchPage"><header><h1>${esc(project.name||'Kitchen CAD')} · ${title}</h1><span>${index+1} / ${pages.length}</span></header><p class="sketchMeta">${meta}</p>${options.draft||unplaced?`<p class="draft">${draftLabel}</p>`:''}<div class="sketchGrid">${rows.map(({part,placement}:any)=>workshopSketchCard(project,part,placement)).join('')}</div><footer>${L(project,'Схема не является программой станка. Перед резом мастер сверяет размеры, кромку, формат листа и пропил; отверстия и столешница согласуются отдельно.','This is not a machine program. Confirm dimensions, edging, sheet stock and kerf before cutting; drilling and countertop are separate.','هذه ليست برنامج آلة. تحقق من المقاسات والحواف واللوح وعرض القطع قبل القص؛ التخريم والسطح منفصلان.')}</footer></section>`;
  }).join('');
  return `<!doctype html><html lang="${langCode(project)}" dir="${isAr(project)?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(L(project,'A4 чертежи деталей','A4 part sketches','رسومات القطع A4'))}</title><style>@page{size:A4 landscape;margin:8mm}*{box-sizing:border-box}body{margin:0;background:#eef1f2;color:#1d2b32;font:11px Arial,sans-serif}.sketchPage{width:100%;height:194mm;padding:3mm;background:white;break-after:page;display:flex;flex-direction:column}.sketchPage:last-child{break-after:auto}header{display:flex;justify-content:space-between;gap:4mm;align-items:flex-start}h1{font-size:16px;margin:0}header span{font-weight:700}.sketchMeta{margin:2mm 0 3mm;font-size:11px}.draft{font-size:14px;font-weight:800;color:#b12222;margin:0 0 2mm}.sketchGrid{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:repeat(2,minmax(0,1fr));gap:3mm;flex:1;min-height:0}.sketchCard{border:1px solid #819096;padding:2mm;min-height:0;display:flex;flex-direction:column;break-inside:avoid}.sketchHead{display:flex;justify-content:space-between;font-size:10px}.sketchName{font-size:12px;font-weight:800;line-height:1.1;margin-top:1mm}.sketchName small{font-size:9px;font-weight:500}.sketchMaterial{color:#45585f;font-size:9px;margin-top:1mm}.sketchCut{margin-top:1.5mm;font-size:11px}.sketchCut b{font-size:13px}.sketchDrawing{width:100%;height:38mm;min-height:25mm;flex:1}.sketchEdges{font-size:9px;line-height:1.3}.sketchFinished{font-size:9px;color:#45585f;margin-top:1mm}footer{font-size:8px;margin-top:2mm;padding-top:1mm;border-top:1px solid #aebbc0}@media print{body{background:#fff}.sketchPage{padding:0;height:194mm}}</style></head><body>${body}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`;
}
export function printWorkshopSketchReport(project:any,model:any,options:{draft?:boolean}={}){const w=window.open('','_blank');if(!w){alert(L(project,'Браузер заблокировал окно печати.','Pop-up blocked.','تم حظر نافذة الطباعة.'));return}w.document.open();w.document.write(workshopSketchReportHtml(project,model,options));w.document.close()}
export function reportHtml(project:any,model:any,moduleId?:string){const furniture=model.modules.filter((m:any)=>!isDisplayOnlyType(m.type)),chosen=moduleId?furniture.filter((m:any)=>m.id===moduleId):furniture,stock=moduleId?'':stockLayoutSheets(project,model),cards=chosen.map((m:any)=>cutCardsSheets(project,m,model.parts.filter((p:any)=>p.moduleId===m.id))).join('');return `<!doctype html><html lang="${langCode(project)}" dir="${isAr(project)?'rtl':'ltr'}"><head><meta charset="utf-8"><title>${esc(L(project,'Карты деталей','Part cards','بطاقات القطع'))}</title><style>@page{size:A4 landscape;margin:7mm}*{box-sizing:border-box}body{margin:0;font:11px Arial,sans-serif;color:#16252b;background:#ddd}.page{width:100%;min-height:185mm;background:#fff;padding:3mm;page-break-after:always}.page:last-child{page-break-after:auto}h1{margin:0 0 1.5mm;font-size:19px}.meta{margin-bottom:1.5mm;color:#51636a}.cutCards{display:grid;grid-template-columns:1fr 1fr;gap:5mm;height:158mm}.cutCard{border:1px solid #aebbc0;border-radius:2mm;padding:3mm;display:flex;flex-direction:column;min-height:73mm}.cutHead{display:flex;justify-content:space-between;gap:4mm;font-size:10px}.cutHead span{font-weight:700}.partDiagram{flex:1;min-height:42mm;margin:1mm 0}.partDrawing{display:block;width:100%;height:36mm}.edgeLegend{display:grid;grid-template-columns:1fr 1fr;gap:1mm 2mm;font-size:7px}.edgeLegend span{padding:1px 3px;border-radius:3px}.edgeOn{color:#5a3fc0;border:1px solid #8f7cf0}.edgeOff{color:#859197;border:1px dashed #c5cccf}.cutSize{font-size:9px;font-weight:800;margin-top:1mm}.cutMeta{display:grid;grid-template-columns:1fr 1fr;gap:1mm 4mm;font-size:7px}.stockGrid{display:grid;grid-template-columns:42% 58%;gap:5mm;height:158mm;align-items:start}.stockDrawing{display:block;max-width:100%;height:154mm;margin:auto}.stockTable{width:100%;border-collapse:collapse;font-size:7px}.stockTable th,.stockTable td{border:1px solid #bdc7ca;padding:1.2mm;text-align:left}.stockTable th{background:#eef2f2}.warning{margin-top:3mm;padding:2mm;border-left:3px solid #d59b37;background:#fff8e8;font-size:8px;line-height:1.4}@media print{body{background:#fff}.page{padding:0}}</style></head><body>${stock}${cards}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`}
export function printReport(project:any,model:any,moduleId?:string){const w=window.open('','_blank');if(!w){alert(isEn(project)?'Pop-up blocked.':'Браузер заблокировал окно печати.');return}w.document.open();w.document.write(reportHtml(project,model,moduleId));w.document.close()}
async function svgToPng(svg:string,name:string){const source=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});try{const bitmap=await createImageBitmap(source),c=document.createElement('canvas');c.width=2240;c.height=1240;const g=c.getContext('2d')!;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/png'));if(blob){blobDownload(blob,name);return}}catch{}const u=URL.createObjectURL(source),img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject();img.src=u}).catch(()=>{});if(img.complete&&img.naturalWidth){const c=document.createElement('canvas');c.width=2240;c.height=1240;const g=c.getContext('2d')!;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(img,0,0,c.width,c.height);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/png'));if(blob)blobDownload(blob,name)}URL.revokeObjectURL(u)}
export function downloadPng(project:any,model:any,moduleId?:string){if(moduleId){const shot=(window as any).__kitchenCadCapture?.();if(shot){fetch(shot).then(r=>r.blob()).then(b=>blobDownload(b,'module-current-scene.png')).catch(()=>{});return}}void svgToPng(overviewSvg(project,model),'kitchen-overview.png')}
