import { cutListCSV } from '../../src/io/cut-list.js';
import { MODULE_TYPES,SUBSTRATES,DECORS,isDisplayOnlyType } from '../../src/catalog/materials.js';
import { explodedCentre } from '../domain/view-math.js';

const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const safe=(s:string)=>s.replace(/[^a-z0-9а-яё._-]+/gi,'-').replace(/^-+|-+$/g,'')||'kitchen-cad';
const blobDownload=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),15000)};
export const downloadJson=(p:any)=>blobDownload(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),`${safe(p.name||'kitchen')}.json`);
export const downloadCsv=(m:any,id?:string)=>{const parts=id?m.parts.filter((p:any)=>p.moduleId===id):m.parts;blobDownload(new Blob([cutListCSV(parts)],{type:'text/csv;charset=utf-8'}),`${id?'module':'project'}-cut-list.csv`)};

const isEn=(p:any)=>p.ui?.language==='en';
const enNames:any={base:'Base cabinet',drawer:'Drawer cabinet',sink:'Sink cabinet',cornerBase:'Base corner cabinet',wall:'Wall cabinet',cornerWall:'Wall corner cabinet',tall:'Tall cabinet',tallOven:'Oven tall cabinet'};
const moduleName=(type:string,en:boolean)=>en?(enNames[type]||type):((MODULE_TYPES as any)[type]||type);
const svgOpen=(w:number,h:number)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" class="drawing"><rect width="100%" height="100%" fill="#fff"/>`;
const txt=(x:number,y:number,s:string,anchor='middle',size=11,weight=700)=>`<text x="${x}" y="${y}" text-anchor="${anchor}" font-size="${size}" font-family="Arial,sans-serif" fill="#26333a" font-weight="${weight}">${esc(s)}</text>`;
function dim(x1:number,y1:number,x2:number,y2:number,label:string){const dx=x2-x1,dy=y2-y1,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,mx=(x1+x2)/2,my=(y1+y2)/2,t=5;return `<g stroke="#6150b8" fill="none"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/><line x1="${x1-nx*t}" y1="${y1-ny*t}" x2="${x1+nx*t}" y2="${y1+ny*t}"/><line x1="${x2-nx*t}" y1="${y2-ny*t}" x2="${x2+nx*t}" y2="${y2+ny*t}"/></g><rect x="${mx-30}" y="${my-9}" width="60" height="17" rx="4" fill="#fff" stroke="#d5d0ed"/>${txt(mx,my+3,label)}`}
const iso=(x:number,y:number,z:number):[number,number]=>[(x-z)*.78,(x+z)*.28-y*.92];
function box(cx:number,cy:number,cz:number,sx:number,sy:number,sz:number,scale:number,ox:number,oy:number){const pts=[[cx-sx/2,cy-sy/2,cz-sz/2],[cx+sx/2,cy-sy/2,cz-sz/2],[cx+sx/2,cy+sy/2,cz-sz/2],[cx-sx/2,cy+sy/2,cz-sz/2],[cx-sx/2,cy-sy/2,cz+sz/2],[cx+sx/2,cy-sy/2,cz+sz/2],[cx+sx/2,cy+sy/2,cz+sz/2],[cx-sx/2,cy+sy/2,cz+sz/2]].map(([x,y,z])=>{const[u,v]=iso(x,y,z);return[ox+u*scale,oy+v*scale]});const p=(ids:number[])=>ids.map(i=>pts[i].join(',')).join(' ');return{pts,top:p([3,2,6,7]),front:p([4,5,6,7]),side:p([1,5,6,2])}}
function axisFor(size:number[],value:number,used:Set<number>){let best=0,d=Infinity;size.forEach((s,i)=>{if(!used.has(i)&&Math.abs(s-value)<d){best=i;d=Math.abs(s-value)}});used.add(best);return best}

function overviewSvg(project:any,model:any){const W=1120,H=620,pad=70,mods=model.modules||[],pts=mods.flatMap((m:any)=>{const a=[] as [number,number][];for(const x of[0,m.width])for(const y of[0,m.height])for(const z of[0,m.depth])a.push(iso(m.x+x,m.y+y,m.z+z));return a}),minU=Math.min(...pts.map(p=>p[0]),0),maxU=Math.max(...pts.map(p=>p[0]),1),minV=Math.min(...pts.map(p=>p[1]),0),maxV=Math.max(...pts.map(p=>p[1]),1),s=Math.min((W-2*pad)/Math.max(1,maxU-minU),(H-2*pad)/Math.max(1,maxV-minV)),ox=pad-minU*s,oy=pad-minV*s;let body='';for(const m of mods){const q=box(m.x+m.width/2,m.y+m.height/2,m.z+m.depth/2,m.width,m.height,m.depth,s,ox,oy),fill=isDisplayOnlyType(m.type)?'#dce3e6':'#eee9df';body+=`<polygon points="${q.front}" fill="${fill}" stroke="#607177"/><polygon points="${q.side}" fill="#d8d4ca" stroke="#607177"/><polygon points="${q.top}" fill="#faf8f2" stroke="#607177"/>`}return `${svgOpen(W,H)}${txt(45,30,isEn(project)?'Project overview':'Общий вид проекта','start',20,800)}${body}</svg>`}
function orthographicSvg(project:any,model:any,module:any,view:'front'|'top'|'side'){const en=isEn(project),parts=model.parts.filter((p:any)=>p.moduleId===module.id),W=1120,H=620,pad=95;const cfg=view==='front'?{a:0,b:1,A:module.width,B:module.height,title:en?'Front':'Фронт'}:view==='top'?{a:0,b:2,A:module.width,B:module.depth,title:en?'Top':'Сверху'}:{a:2,b:1,A:module.depth,B:module.height,title:en?'Side':'Сбоку'};const s=Math.min((W-2*pad)/Math.max(1,cfg.A),(H-2*pad)/Math.max(1,cfg.B));let body='';for(const p of parts){const c=p.center,size=p.size,originA=cfg.a===0?module.x:cfg.a===2?module.z:module.y,originB=cfg.b===0?module.x:cfg.b===2?module.z:module.y,x=pad+(c[cfg.a]-size[cfg.a]/2-originA)*s,y=H-pad-(c[cfg.b]+size[cfg.b]/2-originB)*s,w=Math.max(2,size[cfg.a]*s),h=Math.max(2,size[cfg.b]*s);body+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${p.role==='front'?'#dcebd7':'#f0ede5'}" stroke="#607177"/>`}const x0=pad,y0=H-pad;body+=dim(x0,y0+24,x0+cfg.A*s,y0+24,`${cfg.A} мм`);body+=dim(x0-24,y0,x0-24,y0-cfg.B*s,`${cfg.B} мм`);return `${svgOpen(W,H)}${txt(45,30,`${moduleName(module.type,en)} — ${cfg.title}`,'start',20,800)}${txt(45,52,`${en?'W×H×D':'Ш×В×Г'}: ${module.width} × ${module.height} × ${module.depth} мм`,'start',12,500)}${body}</svg>`}
function explodedSvg(project:any,model:any,module:any){const en=isEn(project),explode=Math.max(0,Math.min(500,Number(project.ui?.explode)||0)),parts=model.parts.filter((p:any)=>p.moduleId===module.id).map((p:any)=>({...p,drawCenter:explodedCentre(p,module,explode)})),W=1120,H=620,MAX=500,ref=[] as [number,number][];for(const x of[-MAX,module.width+MAX])for(const y of[-MAX,module.height+MAX])for(const z of[-MAX,module.depth+MAX])ref.push(iso(module.x+x,module.y+y,module.z+z));const minU=Math.min(...ref.map(p=>p[0])),maxU=Math.max(...ref.map(p=>p[0])),minV=Math.min(...ref.map(p=>p[1])),maxV=Math.max(...ref.map(p=>p[1])),s=Math.min(780/Math.max(1,maxU-minU),500/Math.max(1,maxV-minV)),ox=70-minU*s,oy=85-minV*s,mc=[module.x+module.width/2,module.y+module.height/2,module.z+module.depth/2];let body='';for(const p of parts){const q=box(p.drawCenter[0],p.drawCenter[1],p.drawCenter[2],p.size[0],p.size[1],p.size[2],s,ox,oy),fill=p.role==='front'?'#dcebd7':'#f0ede5';body+=`<polygon points="${q.front}" fill="${fill}" stroke="#607177"/><polygon points="${q.side}" fill="#dad7cf" stroke="#607177"/><polygon points="${q.top}" fill="#faf8f2" stroke="#607177"/>`;const used=new Set<number>(),axes:[[number,number],[number,number]]=[[axisFor(p.size,p.u,used),p.u],[axisFor(p.size,p.v,used),p.v]];for(let k=0;k<2;k++){const [axis,val]=axes[k];let a=q.pts[4],b=q.pts[5];if(axis===1){a=q.pts[5];b=q.pts[6]}else if(axis===2){a=q.pts[0];b=q.pts[4]}const sign=((p.drawCenter[(axis+1)%3]-mc[(axis+1)%3])>=0?1:-1),off=(k?16:9)*sign;body+=dim(a[0],a[1]+off,b[0],b[1]+off,`${Math.round(val)}`)}}return `${svgOpen(W,H)}${txt(45,30,`${moduleName(module.type,en)} — ${en?'Exploded 3D':'Разобранный 3D'}`,'start',20,800)}${txt(45,52,`${en?'Explode':'Разнос'}: ${explode} мм`,'start',12,500)}${body}</svg>`}
function partsTable(project:any,parts:any[]){const en=isEn(project);return `<table><thead><tr><th>#</th><th>ID</th><th>${en?'Part':'Деталь'}</th><th>${en?'Material':'Материал'}</th><th>${en?'Finished':'Готовый размер'}</th><th>${en?'Blank':'Заготовка'}</th><th>${en?'Edge':'Кромка'}</th></tr></thead><tbody>${parts.map((p:any,i:number)=>`<tr><td>${i+1}</td><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(SUBSTRATES[p.substrate]?.name||p.substrate)} / ${esc(DECORS[p.decor]?.name||p.decor)}</td><td>${p.u} × ${p.v} × ${p.thickness}</td><td>${p.blankU} × ${p.blankV} × ${p.thickness}</td><td>${esc(p.edgeType||'')} ${p.edges.join(' / ')}</td></tr>`).join('')}</tbody></table>`}
const page=(title:string,meta:string,body:string,cls='')=>`<section class="page ${cls}"><h1>${esc(title)}</h1><div class="meta">${meta}</div>${body}</section>`;
function orthoSheet(project:any,model:any,module:any){const en=isEn(project),name=moduleName(module.type,en),meta=`${en?'W×H×D':'Ш×В×Г'}: <b>${module.width} × ${module.height} × ${module.depth} мм</b>`;return page(`${name} — ${en?'Dimensions':'Размеры'}`,meta,`<div class="orthoGrid"><div>${orthographicSvg(project,model,module,'front')}</div><div>${orthographicSvg(project,model,module,'top')}</div><div>${orthographicSvg(project,model,module,'side')}</div></div>`,'orthoPage')}
function assemblySheet(project:any,model:any,module:any,scenePng?:string|null){const en=isEn(project),name=moduleName(module.type,en),parts=model.parts.filter((p:any)=>p.moduleId===module.id),explode=Math.max(0,Math.min(500,Number(project.ui?.explode)||0)),meta=`${en?'Explode':'Разнос'}: <b>${explode} мм</b>`;const visual=scenePng?`<div class="sceneShot"><img src="${scenePng}" alt="3D"/></div>`:`<div class="fallback3d">${explodedSvg(project,model,module)}</div>`;return page(`${name} — ${en?'Assembly + cut list':'Сборка + напил'}`,meta,`<div class="assemblyGrid"><div class="visualCol">${visual}</div><div class="tableCol"><h2>${en?'Cut list':'Напил'}</h2>${partsTable(project,parts)}<p class="warning">${en?'3D snapshot uses the current camera/explode state. Verify drilling, fittings, cut-outs and workshop tolerances before production.':'3D-снимок использует текущий ракурс и разнос сцены. Перед производством проверить сверловку, фурнитуру, вырезы и припуски конкретного цеха.'}</p></div></div>`,'assemblyPage')}
function reportHtml(project:any,model:any,moduleId?:string,scenePng?:string|null){const en=isEn(project),furniture=model.modules.filter((m:any)=>!isDisplayOnlyType(m.type)),chosen=moduleId?furniture.filter((m:any)=>m.id===moduleId):furniture,cover=moduleId?'':page(project.name||'Kitchen CAD',`${en?'Room':'Комната'}: ${project.room.width} × ${project.room.depth} × ${project.room.height} мм`,overviewSvg(project,model));return `<!doctype html><html lang="${en?'en':'ru'}"><head><meta charset="utf-8"><title>Kitchen CAD</title><style>@page{size:A4 landscape;margin:7mm}*{box-sizing:border-box}body{margin:0;font:11px Arial,sans-serif;color:#16252b;background:#ddd}.page{width:100%;min-height:185mm;background:#fff;padding:3mm;page-break-after:always}.page:last-child{page-break-after:auto}h1{margin:0 0 1.5mm;font-size:19px}.meta{margin-bottom:1.5mm;color:#51636a}.drawing{width:100%;height:100%;border:0}.orthoGrid{height:157mm;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:4mm}.orthoGrid>div{border:1px solid #ccd5d7;overflow:hidden}.orthoGrid>div:first-child{grid-column:1/3}.assemblyGrid{height:158mm;display:grid;grid-template-columns:1.25fr 1fr;gap:4mm}.visualCol,.tableCol{min-width:0;overflow:hidden}.sceneShot,.fallback3d{height:100%;border:1px solid #ccd5d7;display:flex;align-items:center;justify-content:center;background:#f7f8f8}.sceneShot img{width:100%;height:100%;object-fit:contain}.fallback3d .drawing{height:100%}.tableCol{display:flex;flex-direction:column}.tableCol h2{font-size:14px;margin:0 0 2mm}table{width:100%;border-collapse:collapse;font-size:7px}th,td{border:1px solid #cbd4d7;padding:2px}th{background:#eef2f3}.warning{border-left:3px solid #d79743;padding:4px 6px;background:#fff8ec;font-size:8px;margin-top:2mm}@media print{body{background:#fff}.page{padding:0}}</style></head><body>${cover}${chosen.map((m:any,i:number)=>orthoSheet(project,model,m)+assemblySheet(project,model,m,moduleId&&i===0?scenePng:null)).join('')}<script>setTimeout(()=>window.print(),500)<\/script></body></html>`}
export function printReport(project:any,model:any,moduleId?:string){const scenePng=moduleId?((window as any).__kitchenCadCapture?.()||null):null,w=window.open('','_blank');if(!w){alert(isEn(project)?'Pop-up blocked.':'Браузер заблокировал окно печати.');return}w.document.open();w.document.write(reportHtml(project,model,moduleId,scenePng));w.document.close()}
async function svgToPng(svg:string,name:string){const source=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});try{const bitmap=await createImageBitmap(source),c=document.createElement('canvas');c.width=2240;c.height=1240;const g=c.getContext('2d')!;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/png'));if(blob){blobDownload(blob,name);return}}catch{}const u=URL.createObjectURL(source),img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject();img.src=u}).catch(()=>{});if(img.complete&&img.naturalWidth){const c=document.createElement('canvas');c.width=2240;c.height=1240;const g=c.getContext('2d')!;g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(img,0,0,c.width,c.height);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/png'));if(blob)blobDownload(blob,name)}URL.revokeObjectURL(u)}
export function downloadPng(project:any,model:any,moduleId?:string){if(moduleId){const shot=(window as any).__kitchenCadCapture?.();if(shot){fetch(shot).then(r=>r.blob()).then(b=>blobDownload(b,'module-current-scene.png')).catch(()=>{});return}}void svgToPng(overviewSvg(project,model),'kitchen-overview.png')}
