import { appearance, isApplianceType, isDisplayOnlyType, isRoomElementType, isDrawerType, isCornerType, isWallMountedType } from '../catalog/materials.js';
import { layoutProject, round } from './project.js';
import { buildCabinetSupportObjects } from './supports.js';

export function blankSize(u,v,edges){const values=[u,v,...edges];if(edges.length!==4||values.some(n=>!Number.isFinite(n))||edges.some(n=>n<0))throw new Error('Некорректная кромка');const a=round(u-edges[0]-edges[1]),b=round(v-edges[2]-edges[3]);if(a<=0||b<=0)throw new Error('Кромка больше размера детали');return[a,b]}

function pushBox(objects,m,id,suffix,size,center,app,kind='accessory',shape='box'){objects.push({id:`${id}-${suffix}`,moduleId:m.id,kind,role:kind,shape,size,center:[center[0]+m.x,center[1]+m.y,center[2]+m.z],appearance:app})}
function displayGeometry(m,id,objects){const w=m.width,h=m.height,d=m.depth,white=appearance('white','#d8ddde'),dark=appearance('graphite','#1f2b31'),gray=appearance('graphite','#8c989c'),metal=appearance('graphite','#aab2b4');
 pushBox(objects,m,id,'BODY',[w,h,d],[w/2,h/2,d/2],white,isRoomElementType(m.type)?'room-element':'appliance');
 if(m.type==='washer'){pushBox(objects,m,id,'PANEL',[w-18,82,10],[w/2,h-58,d+5],gray,'appliance-detail');pushBox(objects,m,id,'SCREEN',[126,34,12],[w*.67,h-55,d+12],dark,'appliance-detail');pushBox(objects,m,id,'PORT',[w*.54,w*.54,22],[w/2,h*.46,d+15],metal,'appliance-port','disc');pushBox(objects,m,id,'GLASS',[w*.42,w*.42,28],[w/2,h*.46,d+25],dark,'appliance-glass','disc')}
 else if(m.type==='dishwasher'){pushBox(objects,m,id,'DOOR',[w-16,h-55,16],[w/2,(h-55)/2+10,d+10],metal,'appliance-detail');pushBox(objects,m,id,'CONTROL',[w-36,48,12],[w/2,h-38,d+13],dark,'appliance-detail');pushBox(objects,m,id,'HANDLE',[w*.52,16,20],[w/2,h-92,d+24],gray,'handle')}
 else if(m.type==='oven'){pushBox(objects,m,id,'FRAME',[w-28,h-60,18],[w/2,h/2-5,d+12],dark,'appliance-detail');pushBox(objects,m,id,'GLASS',[w-82,h*.54,22],[w/2,h*.40,d+24],dark,'appliance-detail');pushBox(objects,m,id,'CONTROL',[w-72,80,18],[w/2,h-62,d+23],gray,'appliance-detail');pushBox(objects,m,id,'HANDLE',[w*.68,18,22],[w/2,h*.66,d+32],metal,'handle')}
 else if(m.type==='fridge'||m.type==='freezer'){pushBox(objects,m,id,'DOOR1',[w-22,h*.58,18],[w/2,h*.69,d+12],metal,'appliance-detail');pushBox(objects,m,id,'DOOR2',[w-22,h*.38,18],[w/2,h*.20,d+12],metal,'appliance-detail');pushBox(objects,m,id,'HANDLE1',[18,h*.22,24],[w-46,h*.69,d+28],dark,'handle');pushBox(objects,m,id,'HANDLE2',[18,h*.16,24],[w-46,h*.22,d+28],dark,'handle')}
 else if(m.type==='microwave'){pushBox(objects,m,id,'GLASS',[w-70,h-85,18],[w*.43,h*.48,d+14],dark,'appliance-detail');pushBox(objects,m,id,'CONTROL',[95,h-70,18],[w-65,h*.5,d+14],gray,'appliance-detail');pushBox(objects,m,id,'HANDLE',[15,h*.45,22],[w*.73,h*.5,d+25],metal,'handle')}
 else if(m.type==='hood'){pushBox(objects,m,id,'CANOPY',[w,90,d],[w/2,45,d/2],metal,'appliance-detail');pushBox(objects,m,id,'CHIMNEY',[Math.min(240,w*.45),h-75,Math.min(180,d*.7)],[w/2,(h+75)/2,d*.35],gray,'appliance-detail')}
 else if(m.type==='window'){pushBox(objects,m,id,'GLASS',[Math.max(80,w-70),Math.max(80,h-70),12],[w/2,h/2,d+4],appearance('graphite','#9cc9d8'),'window-glass');pushBox(objects,m,id,'MULLION',[28,h-70,24],[w/2,h/2,d+12],white,'room-detail');pushBox(objects,m,id,'SILL',[w+80,35,160],[w/2,-18,80],white,'room-detail')}
 else if(m.type==='door'){pushBox(objects,m,id,'PANEL',[w-80,h-80,35],[w/2,h/2,d+12],appearance('oak','#b98555'),'door-panel');pushBox(objects,m,id,'HANDLE',[32,32,55],[w*.78,h*.48,d+45],metal,'handle')}
}

function frontExtras(m,id,objects,x,y,z,w,h,hingeSide){const dark=appearance('graphite','#384349'),glass=appearance('graphite','#26343b');
 if(m.frontStyle==='glass')pushBox(objects,m,id,`GLASS-${x}`,[Math.max(40,w-90),Math.max(40,h-90),5],[x,y,z+10],glass,'front-insert');
 if(['frame','shaker'].includes(m.frontStyle)){const rail=m.frontStyle==='shaker'?55:42;pushBox(objects,m,id,`FL-${x}`,[rail,h-30,7],[x-w/2+rail/2+12,y,z+9],dark,'front-decoration');pushBox(objects,m,id,`FR-${x}`,[rail,h-30,7],[x+w/2-rail/2-12,y,z+9],dark,'front-decoration');pushBox(objects,m,id,`FT-${x}`,[w-30,rail,7],[x,y+h/2-rail/2-12,z+9],dark,'front-decoration');pushBox(objects,m,id,`FB-${x}`,[w-30,rail,7],[x,y-h/2+rail/2-12,z+9],dark,'front-decoration')}
 if(['slatted','louvered'].includes(m.frontStyle))for(let k=-Math.floor(w/2)+28;k<w/2-18;k+=(m.frontStyle==='louvered'?28:36))pushBox(objects,m,id,`SL-${x}-${k}`,[10,h-24,6],[x+k,y,z+9],dark,'front-decoration');
 if(m.handleStyle==='bar')pushBox(objects,m,id,`HANDLE-${x}`,[Math.min(180,w*.42),12,18],[x,y+h/2-64,z+19],dark,'handle');else if(m.handleStyle==='knob'){const knobX=hingeSide==='right'?x-w*.24:hingeSide==='left'?x+w*.24:x;pushBox(objects,m,id,`KNOB-${x}`,[24,24,22],[knobX,y,z+20],dark,'handle')}else if(m.handleStyle==='integrated'||m.frontStyle==='handleless')pushBox(objects,m,id,`GRIP-${x}`,[Math.max(60,w-70),14,12],[x,y+h/2-20,z+15],dark,'handle')
}
function frontFinish(m,override={}){const decor=override.decor||m.frontDecor,color=override.color||(override.decor?undefined:m.frontColor);return{decor,appearance:appearance(decor,color,m.gloss,m.grain)}}
function moduleBounds(m){const r=((Math.round((Number(m.rotationY)||0)/90)*90)%360+360)%360,fw=(r===90||r===270)?m.depth:m.width,fd=(r===90||r===270)?m.width:m.depth,cx=m.x+m.width/2,cz=m.z+m.depth/2;return{x:cx-fw/2,z:cz-fd/2,width:fw,depth:fd}}
function rectsOverlap(a,b){const A=moduleBounds(a),B=moduleBounds(b);return A.x<B.x+B.width&&A.x+A.width>B.x&&A.z<B.z+B.depth&&A.z+A.depth>B.z}

export function buildProject(project){
 const modules=layoutProject(project),parts=[],objects=[],warnings=[],issues=[];
 modules.forEach((m,index)=>{
  const w=m.width,h=m.height,d=m.depth,t=m.board,b=m.back,id=`M${String(index+1).padStart(2,'0')}`;
  const mb=moduleBounds(m),out=mb.x<0||mb.z<0||mb.x+mb.width>project.room.width||mb.z+mb.depth>project.room.depth||m.y+h>project.room.height;
  if(out&&!isRoomElementType(m.type)){issues.push({type:'module-out',moduleId:m.id,message:`${id}: модуль выходит за пределы комнаты.`});warnings.push(`${id}: модуль выходит за пределы комнаты.`)}
  if(isDisplayOnlyType(m.type)){displayGeometry(m,id,objects);return}
  const backOverlay=m.backMode==='overlay',bodyDepth=backOverlay?d-b:d,bottomUnder=m.bottomMode==='under',topOverlay=['wall','cornerWall','cornerWallBlind','cornerWallDiagonal','cornerWallL'].includes(m.type)&&m.topMode==='overlay',lower=bottomUnder?t:0,upper=topOverlay?t:0,sideH=h-lower-upper,inner=w-2*t,frontsEnabled=m.frontEnabled!==false,baseApp=appearance(m.bodyDecor,m.bodyColor,false),faceApp=appearance(m.frontDecor,m.frontColor,m.gloss,m.grain);
  const add=(suffix,name,u,v,thick,edges,size,center,role='body',opts={})=>{const front=role==='front',raw=blankSize(u,v,edges),partId=`${id}-${suffix}`,decor=opts.decor||(front?m.frontDecor:m.bodyDecor),app=opts.appearance||(front?faceApp:baseApp),substrate=role==='back'?'mdf':front?m.frontSubstrate:m.bodySubstrate,part={id:partId,moduleId:m.id,moduleCode:id,name,role,u:round(u),v:round(v),thickness:thick,blankU:raw[0],blankV:raw[1],edges,edgeType:front?m.frontEdgeType:m.bodyEdgeType,substrate,decor,grain:front?m.grain:'v',size,center:[center[0]+m.x,center[1]+m.y,center[2]+m.z],appearance:app,hingeSide:opts.hingeSide||null,hingeMountPartId:opts.hingeMountPartId||null,hingeType:opts.hingeType||null,rotationY:opts.rotationY||0};parts.push(part);objects.push({...part,kind:'part'});return part};
  add('SL','Боковина левая',bodyDepth,sideH,t,[0,m.bodyEdge,0,0],[t,sideH,bodyDepth],[t/2,lower+sideH/2,(backOverlay?b:0)+bodyDepth/2]);
  add('SR','Боковина правая',bodyDepth,sideH,t,[0,m.bodyEdge,0,0],[t,sideH,bodyDepth],[w-t/2,lower+sideH/2,(backOverlay?b:0)+bodyDepth/2]);
  if(bottomUnder)add('BT','Дно под боковинами',w,bodyDepth,t,[0,0,0,m.bodyEdge],[w,t,bodyDepth],[w/2,t/2,(backOverlay?b:0)+bodyDepth/2]);else add('BT','Дно между боковинами',inner,bodyDepth,t,[0,0,0,m.bodyEdge],[inner,t,bodyDepth],[w/2,t/2,(backOverlay?b:0)+bodyDepth/2]);
  if(m.backMode==='none'){}else if(backOverlay)add('BK','Задняя стенка накладная',w,h,b,[0,0,0,0],[w,h,b],[w/2,h/2,b/2],'back');else if(m.backMode==='inset')add('BK','Задняя стенка вкладная',inner,Math.max(40,h-lower-upper-2*t),b,[0,0,0,0],[inner,Math.max(40,h-lower-upper-2*t),b],[w/2,lower+(h-lower-upper)/2,b/2],'back');
  if(['wall','cornerWall','cornerWallBlind','cornerWallDiagonal','cornerWallL'].includes(m.type)){if(topOverlay)add('TP','Крышка сверху боковин',w,bodyDepth,t,[0,0,0,m.bodyEdge],[w,t,bodyDepth],[w/2,h-t/2,(backOverlay?b:0)+bodyDepth/2]);else add('TP','Верх между боковинами',inner,bodyDepth,t,[0,0,0,m.bodyEdge],[inner,t,bodyDepth],[w/2,h-t/2,(backOverlay?b:0)+bodyDepth/2])}
  else{add('RF','Передняя верхняя планка',inner,100,t,[0,0,0,m.bodyEdge],[inner,t,100],[w/2,h-t/2,d-50]);add('RR','Задняя верхняя планка',inner,100,t,[0,0,0,0],[inner,100,t],[w/2,h-50,(backOverlay?b:0)+t/2]);if(m.feet>20&&m.legStyle==='hidden')add('PL','Цоколь',w,m.feet-10,t,[0,0,0,m.bodyEdge],[w,m.feet-10,t],[w/2,-(m.feet-10)/2,d-65])}
  objects.push(...buildCabinetSupportObjects(m,id));
  if(!['sink','drawer'].includes(m.type)&&m.shelfCount>0){const sw=inner-2,sd=Math.max(80,bodyDepth-20);for(let s=0;s<m.shelfCount;s++){const sy=lower+(s+1)*(sideH/(m.shelfCount+1));add(`SH${s+1}`,`Полка ${s+1}`,sw,sd,t,[0,0,0,m.bodyEdge],[sw,t,sd],[w/2,sy,(backOverlay?b:0)+sd/2])}}
  if(['cornerBaseBlind','cornerWallBlind'].includes(m.type)){
   const g=m.gap,opening=Math.max(250,Math.min(m.cornerOpening||450,w-260)),openingSide=m.cornerOpeningSide==='left'?'left':'right',fh=h-2*g,muntinW=Math.max(28,Math.min(Number(m.cornerMuntinWidth)||70,150,w-opening-4*g-120)),blindW=Math.max(120,w-opening-muntinW-4*g),start=openingSide==='left'?g:w-g-opening,blindX=openingSide==='left'?w-g-blindW/2:g+blindW/2,muntinX=openingSide==='left'?start+opening+g+muntinW/2:start-g-muntinW/2,hingeSide=openingSide==='left'?'right':'left',muntinPartId=`${id}-MS`;
   add('BF','Глухая панель корпуса',blindW,fh,t,[m.bodyEdge,m.bodyEdge,m.bodyEdge,m.bodyEdge],[blindW,fh,t],[blindX,h/2,d-t/2],'body');
   add('MS','Монтажная стойка петель',muntinW,fh,t,[m.bodyEdge,m.bodyEdge,m.bodyEdge,m.bodyEdge],[muntinW,fh,t],[muntinX,h/2,d-t/2],'body');
   if(frontsEnabled){const x=start+opening/2,ov=(m.frontOverrides||[])[0]||{},finish=frontFinish(m,ov);add('F1','Фасад 1',opening,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[opening,fh,m.frontThickness],[x,h/2,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide,hingeMountPartId:muntinPartId,hingeType:'blind-corner-95'});frontExtras(m,id,objects,x,h/2,d+m.frontThickness+4,opening,fh,hingeSide)}
   warnings.push(`${id}: глухой угол — проём ${opening} мм ${openingSide==='left'?'слева':'справа'}, петли крепятся к монтажной стойке ${round(muntinW)} мм; проверить карту сверления выбранной фурнитуры.`);
  } else if(['cornerBaseDiagonal','cornerWallDiagonal'].includes(m.type)){
   const arm=Math.min(w,d,Number(m.cornerRunDepth)||Number(m.cornerWingDepth)||(m.type.includes('Wall')?320:600)),dx=w-arm,dz=arm-d,faceLen=Math.max(180,Math.hypot(dx,dz)),n=Math.max(1,Math.min(2,m.doorCount||1)),fh=h-2*m.gap,fw=(faceLen-(n+1)*m.gap)/n,rot=Math.atan2(d-arm,w-arm);
   if(frontsEnabled)for(let j=0;j<n;j++){const along=m.gap+fw/2+j*(fw+m.gap),q=along/faceLen,x=arm+dx*q,z=d+dz*q,ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov),hingeSide=ov.hingeSide||(n===1?'left':j===0?'left':'right');add(`F${j+1}`,`Диагональный фасад ${j+1}`,fw,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[fw,fh,m.frontThickness],[x,h/2,z],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide,rotationY:rot})}
   warnings.push(`${id}: диагональный корпус остаётся предварительным; фасад и его угол уже входят в деталировку, корпус проверить перед производством.`);
  } else if(['cornerBaseL','cornerWallL'].includes(m.type)){
   const arm=Math.min(w,d,Number(m.cornerRunDepth)||Number(m.cornerWingDepth)||(m.type.includes('Wall')?320:600)),fh=h-2*m.gap,lenX=Math.max(120,w-arm-m.gap),lenZ=Math.max(120,d-arm-m.gap),ovs=m.frontOverrides||[],ov1=ovs[0]||{},ov2=ovs[1]||{},finish1=frontFinish(m,ov1),finish2=frontFinish(m,ov2);
   if(frontsEnabled){add('F1','L-фасад 1',lenX,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[lenX,fh,m.frontThickness],[arm+lenX/2,h/2,arm+m.frontThickness/2],'front',{decor:finish1.decor,appearance:finish1.appearance,hingeSide:ov1.hingeSide||'right'});add('F2','L-фасад 2',lenZ,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[lenZ,fh,m.frontThickness],[arm+m.frontThickness/2,h/2,arm+lenZ/2],'front',{decor:finish2.decor,appearance:finish2.appearance,hingeSide:ov2.hingeSide||'left',rotationY:Math.PI/2})}
   warnings.push(`${id}: L-корпус остаётся предварительным; два фасада уже входят в деталировку, стык корпуса проверить перед производством.`);
  } else if(isDrawerType(m.type)){
   const n=Math.max(1,Math.min(6,m.drawerCount||3)),fh=(h-(n+1)*m.gap)/n;
   for(let j=0;j<n;j++){const y=m.gap+fh/2+j*(fh+m.gap),ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov);add(`F${j+1}`,`Фасад ящика ${j+1}`,w-2*m.gap,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[w-2*m.gap,fh,m.frontThickness],[w/2,y,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance});frontExtras(m,id,objects,w/2,y,d+m.frontThickness+4,w-2*m.gap,fh)}
   warnings.push(`${id}: показаны фасады ящиков; направляющие и короба ящиков пока не входят в напил.`)
  } else {
   const n=m.doorCount>0?m.doorCount:(w>650?2:1),totalW=w+m.frontOverhangLeft+m.frontOverhangRight,fw=(totalW-2*m.gap-(n-1)*m.gap)/n,fh=h+m.frontOverhangTop+m.frontOverhangBottom-2*m.gap,start=-m.frontOverhangLeft+m.gap;
   if(frontsEnabled)for(let j=0;j<n;j++){const x=start+fw/2+j*(fw+m.gap),y=h/2+(m.frontOverhangTop-m.frontOverhangBottom)/2,ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov),hingeSide=ov.hingeSide||(n===1?'left':j===0?'left':j===n-1?'right':j%2?'right':'left');add(`F${j+1}`,`Фасад ${j+1}`,fw,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[fw,fh,m.frontThickness],[x,y,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide});frontExtras(m,id,objects,x,y,d+m.frontThickness+4,fw,fh,hingeSide)}
  }
  if(isCornerType(m.type))warnings.push(`${id}: угловой модуль пока показан как параметрический габаритный корпус. Перед производством нужен отдельный профиль углового стыка/фасада.`);
  if(m.type==='tallOven')warnings.push(`${id}: ниша под духовку пока не вырезает корпус автоматически — высоту ниши нужно сверить по конкретной технике.`);
  if(m.width>900)warnings.push(`${id}: широкий пролёт; проверить прогиб и опоры.`);
 });
 const roomTypes=new Set(['window','door']),floor=modules.filter(m=>!isWallMountedType(m.type)&&!roomTypes.has(m.type)),baseTypes=new Set(['base','drawer','sink','cornerBase','cornerBaseBlind','cornerBaseDiagonal','cornerBaseL']),bases=floor.filter(m=>baseTypes.has(m.type)),top=project.countertop;
 for(let i=0;i<floor.length;i++)for(let j=i+1;j<floor.length;j++)if(rectsOverlap(floor[i],floor[j])){const a=floor[i],b=floor[j],cornerAppliance=(isCornerType(a.type)&&isApplianceType(b.type))||(isCornerType(b.type)&&isApplianceType(a.type)),message=cornerAppliance?'Техника пересекает угловой шкаф. Её нужно ставить отдельным проёмом или в предназначенный для неё модуль рядом, а не внутрь углового корпуса.':'Есть пересечение напольных модулей.';issues.push({type:cornerAppliance?'appliance-corner-overlap':'overlap',moduleId:a.id,otherId:b.id,message});warnings.push(message)}
 const autoStart=bases.length?Math.min(...bases.map(m=>m.x)):0,autoEnd=bases.length?Math.max(...bases.map(m=>m.x+m.width)):0,autoLength=Math.max(0,autoEnd-autoStart),topLength=top.lengthMode==='manual'?top.length:autoLength+2*top.overhang,topX=top.lengthMode==='manual'?top.offsetX:autoStart-top.overhang,topZ=Number.isFinite(top.offsetZ)?top.offsetZ:0,topY=Number.isFinite(top.elevation)?top.elevation:(bases.length?Math.max(...bases.map(m=>m.y+m.height)):860);
 let countertop=null;
 if(top.enabled&&bases.length){countertop={id:'CT-01',length:topLength,depth:top.depth,thickness:top.thickness,elevation:topY,x:topX,z:topZ};const ctOut=topX<0||topX+topLength>project.room.width||topZ<0||topZ+top.depth>project.room.depth||topY+top.thickness>project.room.height,uncovered=bases.some(m=>m.x<topX||m.x+m.width>topX+topLength||m.z<topZ||m.z+m.depth>topZ+top.depth);if(ctOut){issues.push({type:'countertop-out'});warnings.push('Столешница выходит за пределы комнаты.')}if(uncovered){issues.push({type:'countertop-cover'});warnings.push('Столешница не перекрывает все нижние шкафы.')}objects.push({id:'CT-01',kind:'countertop',role:'countertop',moduleId:null,size:[topLength,top.thickness,top.depth],center:[topX+topLength/2,topY+top.thickness/2,topZ+top.depth/2],appearance:appearance(top.decor,top.color,top.gloss),invalid:ctOut||uncovered})}
 if(countertop){const required=Math.max(5,Math.min(60,Number(project.defaults?.washerClearance)||15));for(const wm of modules.filter(m=>m.type==='washer')){const overlapX=wm.x<countertop.x+countertop.length&&wm.x+wm.width>countertop.x,overlapZ=wm.z<countertop.z+countertop.depth&&wm.z+wm.depth>countertop.z;if(overlapX&&overlapZ){const clearance=round(countertop.elevation-(wm.y+wm.height));if(clearance<required){issues.push({type:'washer-clearance',moduleId:wm.id,clearance,required});warnings.push(`Стиральная машина: зазор до низа столешницы ${clearance} мм, требуется минимум ${required} мм.`)}}}for(const bm of bases){const delta=round(countertop.elevation-(bm.y+bm.height));if(Math.abs(delta)>2)warnings.push(`${bm.type}: верх корпуса отличается от низа столешницы на ${delta} мм (корпус + ножки = ${bm.y+bm.height} мм).`)}}
 const fixtures=[];
 for(const f of project.fixtures||[]){const m=modules.find(x=>x.id===f.targetModuleId);if(!m)continue;const blind=m.type==='cornerBaseBlind',opening=blind?Math.max(250,Math.min(m.cornerOpening||450,m.width-260)):m.width,openingSide=m.cornerOpeningSide==='left'?'left':'right',openingStart=blind?(openingSide==='left'?m.gap:m.width-m.gap-opening):10,openingEnd=blind?openingStart+opening:m.width-10,baseX=blind?openingStart+opening/2:m.width/2,localX=baseX+f.offsetX,localZ=m.depth/2+f.offsetZ,x=m.x+localX,z=m.z+localZ,y=(countertop?.elevation??(m.y+m.height))+(countertop?.thickness??top.thickness)+3,margin=blind?20:0,fits=localX-f.width/2>=openingStart+margin&&localX+f.width/2<=openingEnd-margin&&localZ-f.depth/2>=10&&localZ+f.depth/2<=top.depth-10;fixtures.push({...f,x,y,z,fits});objects.push({id:f.id,moduleId:m.id,kind:f.type==='sink'?'fixture-sink':'fixture-hob',role:'fixture',size:[f.width,12,f.depth],center:[x,y,z],appearance:appearance('graphite',f.type==='sink'?'#aeb7b9':'#161d20'),invalid:!fits});if(!fits){issues.push({type:'fixture',fixtureId:f.id,moduleId:m.id});warnings.push(`${f.type==='sink'?'Раковина':'Варочная поверхность'} не помещается${blind?' в доступный проём глухого углового модуля':''}.`)}}
 warnings.push('Предварительная деталировка: крепёж, сверление, петли, направляющие, нагрузки и припуски цеха требуют проверки.');
 const minX=Math.min(0,...modules.map(m=>m.x)),maxX=Math.max(project.room.width,...modules.map(m=>m.x+m.width));
 return{modules,parts,objects,warnings:[...new Set(warnings)],issues,fixtures,countertop,width:Math.max(0,maxX-minX),height:Math.max(900,...modules.map(m=>m.y+m.height)),depth:Math.max(620,...modules.map(m=>m.z+m.depth+(m.frontThickness||0)+2))};
}
