import { appearance, inferMaterialProductId, isApplianceType, isDisplayOnlyType, isRoomElementType, isDrawerType, isCornerType, isWallMountedType } from '../catalog/materials.js';
import { layoutProject, round } from './project.js';
import { buildCabinetSupportObjects } from './supports.js';
import { applianceBayMeasurements, applianceHobApprovalSignature } from './appliance-bay.js';

export function blankSize(u,v,edges){const values=[u,v,...edges];if(edges.length!==4||values.some(n=>!Number.isFinite(n))||edges.some(n=>n<0))throw new Error('Некорректная кромка');const a=round(u-edges[0]-edges[1]),b=round(v-edges[2]-edges[3]);if(a<=0||b<=0)throw new Error('Кромка больше размера детали');return[a,b]}

function pushBox(objects,m,id,suffix,size,center,app,kind='accessory',shape='box',meta={}){objects.push({id:`${id}-${suffix}`,moduleId:m.id,kind,role:kind,shape,size,center:[center[0]+m.x,center[1]+m.y,center[2]+m.z],appearance:app,...meta})}
function displayGeometry(m,id,objects){const w=m.width,h=m.height,d=m.depth,white=appearance('white','#d8ddde'),dark=appearance('graphite','#1f2b31'),gray=appearance('graphite','#8c989c'),metal=appearance('graphite','#aab2b4');
 pushBox(objects,m,id,'BODY',[w,h,d],[w/2,h/2,d/2],white,isRoomElementType(m.type)?'room-element':'appliance');
 if(m.type==='washer'){pushBox(objects,m,id,'PANEL',[w-18,82,10],[w/2,h-58,d+5],gray,'appliance-detail');pushBox(objects,m,id,'SCREEN',[126,34,12],[w*.67,h-55,d+12],dark,'appliance-detail');pushBox(objects,m,id,'PORT',[w*.54,w*.54,22],[w/2,h*.46,d+15],metal,'appliance-port','disc');pushBox(objects,m,id,'GLASS',[w*.42,w*.42,28],[w/2,h*.46,d+25],dark,'appliance-glass','disc')}
 else if(m.type==='dishwasher'){pushBox(objects,m,id,'DOOR',[w-16,h-55,16],[w/2,(h-55)/2+10,d+10],metal,'appliance-detail');pushBox(objects,m,id,'CONTROL',[w-36,48,12],[w/2,h-38,d+13],dark,'appliance-detail');pushBox(objects,m,id,'HANDLE',[w*.52,16,20],[w/2,h-92,d+24],gray,'handle')}
 else if(m.type==='oven'){pushBox(objects,m,id,'FRAME',[w-28,h-60,18],[w/2,h/2-5,d+12],dark,'appliance-detail');pushBox(objects,m,id,'GLASS',[w-82,h*.54,22],[w/2,h*.40,d+24],dark,'appliance-detail');pushBox(objects,m,id,'CONTROL',[w-72,80,18],[w/2,h-62,d+23],gray,'appliance-detail');pushBox(objects,m,id,'HANDLE',[w*.68,18,22],[w/2,h*.66,d+32],metal,'handle')}
 else if(m.type==='fridge'||m.type==='freezer'){pushBox(objects,m,id,'DOOR1',[w-22,h*.58,18],[w/2,h*.69,d+12],metal,'appliance-detail');pushBox(objects,m,id,'DOOR2',[w-22,h*.38,18],[w/2,h*.20,d+12],metal,'appliance-detail');pushBox(objects,m,id,'HANDLE1',[18,h*.22,24],[w-46,h*.69,d+28],dark,'handle');pushBox(objects,m,id,'HANDLE2',[18,h*.16,24],[w-46,h*.22,d+28],dark,'handle')}
 else if(m.type==='microwave'){pushBox(objects,m,id,'GLASS',[w-70,h-85,18],[w*.43,h*.48,d+14],dark,'appliance-detail');pushBox(objects,m,id,'CONTROL',[95,h-70,18],[w-65,h*.5,d+14],gray,'appliance-detail');pushBox(objects,m,id,'HANDLE',[15,h*.45,22],[w*.73,h*.5,d+25],metal,'handle')}
 else if(m.type==='hood'){
  if(h<=260){
   pushBox(objects,m,id,'HOUSING',[w,Math.max(90,h-32),Math.max(140,d-24)],[w/2,Math.max(90,h-32)/2,Math.max(140,d-24)/2],gray,'appliance-detail');
   pushBox(objects,m,id,'INTAKE',[w,32,d],[w/2,16,d/2],dark,'appliance-detail');
  }else{
   pushBox(objects,m,id,'CANOPY',[w,90,d],[w/2,45,d/2],metal,'appliance-detail');
   pushBox(objects,m,id,'CHIMNEY',[Math.min(240,w*.45),h-75,Math.min(180,d*.7)],[w/2,(h+75)/2,d*.35],gray,'appliance-detail');
  }
 }
 else if(m.type==='window'){pushBox(objects,m,id,'GLASS',[Math.max(80,w-70),Math.max(80,h-70),12],[w/2,h/2,d+4],appearance('graphite','#9cc9d8'),'window-glass');pushBox(objects,m,id,'MULLION',[28,h-70,24],[w/2,h/2,d+12],white,'room-detail');pushBox(objects,m,id,'SILL',[w+80,35,160],[w/2,-18,80],white,'room-detail')}
 else if(m.type==='door'){pushBox(objects,m,id,'PANEL',[w-80,h-80,35],[w/2,h/2,d+12],appearance('oak','#b98555'),'door-panel');pushBox(objects,m,id,'HANDLE',[32,32,55],[w*.78,h*.48,d+45],metal,'handle')}
}

function embeddedApplianceGeometry(m,id,objects,localX,localZ=0,invalid=false){
 const type=m.applianceBay,washer=type==='washer',width=Number(m.applianceWidth)||598,height=Number(m.applianceHeight)||(washer?845:815),depth=Number(m.applianceDepth)||(washer?590:550),fake={...m,type,width,height,depth,x:m.x+localX,y:m.y-m.feet,z:m.z+localZ,feet:0};
 const start=objects.length;displayGeometry(fake,`${id}-BUILTIN`,objects);
 for(const object of objects.slice(start)){object.moduleId=m.id;object.embeddedAppliance=true;object.applianceType=type;object.invalid=invalid}
}

function frontExtras(m,id,objects,x,y,z,w,h,hingeSide,parentFrontId){const dark=appearance('graphite','#384349'),glass=appearance('graphite','#26343b'),meta={parentFrontId};
 if(m.frontStyle==='glass')pushBox(objects,m,id,`GLASS-${x}`,[Math.max(40,w-90),Math.max(40,h-90),5],[x,y,z+10],glass,'front-insert','box',meta);
 if(['frame','shaker'].includes(m.frontStyle)){const rail=m.frontStyle==='shaker'?55:42;pushBox(objects,m,id,`FL-${x}`,[rail,h-30,7],[x-w/2+rail/2+12,y,z+9],dark,'front-decoration','box',meta);pushBox(objects,m,id,`FR-${x}`,[rail,h-30,7],[x+w/2-rail/2-12,y,z+9],dark,'front-decoration','box',meta);pushBox(objects,m,id,`FT-${x}`,[w-30,rail,7],[x,y+h/2-rail/2-12,z+9],dark,'front-decoration','box',meta);pushBox(objects,m,id,`FB-${x}`,[w-30,rail,7],[x,y-h/2+rail/2-12,z+9],dark,'front-decoration','box',meta)}
 if(['slatted','louvered'].includes(m.frontStyle))for(let k=-Math.floor(w/2)+28;k<w/2-18;k+=(m.frontStyle==='louvered'?28:36))pushBox(objects,m,id,`SL-${x}-${k}`,[10,h-24,6],[x+k,y,z+9],dark,'front-decoration','box',meta);
 if(m.handleStyle==='bar')pushBox(objects,m,id,`HANDLE-${x}`,[Math.min(180,w*.42),12,18],[x,y+h/2-64,z+19],dark,'handle','box',meta);else if(m.handleStyle==='knob'){const knobX=hingeSide==='right'?x-w*.24:hingeSide==='left'?x+w*.24:x;pushBox(objects,m,id,`KNOB-${x}`,[24,24,22],[knobX,y,z+20],dark,'handle','box',meta)}else if(m.handleStyle==='integrated'||m.frontStyle==='handleless')pushBox(objects,m,id,`GRIP-${x}`,[Math.max(60,w-70),14,12],[x,y+h/2-20,z+15],dark,'handle','box',meta)
}
function frontFinish(m,override={}){const decor=override.decor||m.frontDecor,color=override.color||(override.decor?undefined:m.frontColor);return{decor,appearance:appearance(decor,color,m.gloss,m.grain)}}
function moduleBounds(m){const r=((Math.round((Number(m.rotationY)||0)/90)*90)%360+360)%360,fw=(r===90||r===270)?m.depth:m.width,fd=(r===90||r===270)?m.width:m.depth,cx=m.x+m.width/2,cz=m.z+m.depth/2;return{x:cx-fw/2,z:cz-fd/2,width:fw,depth:fd}}
function rectsOverlap(a,b){const A=moduleBounds(a),B=moduleBounds(b);return A.x<B.x+B.width&&A.x+A.width>B.x&&A.z<B.z+B.depth&&A.z+A.depth>B.z}
function cabinetFrontProjection(m){const t=Math.max(0,Number(m.frontThickness)||18),style=String(m.frontStyle||''),handle=String(m.handleStyle||'none');let projection=t+2;if(['frame','shaker'].includes(style))projection=Math.max(projection,t+16.5);if(['slatted','louvered'].includes(style))projection=Math.max(projection,t+16);if(handle==='bar')projection=Math.max(projection,t+32);else if(handle==='knob')projection=Math.max(projection,t+35);else if(handle==='integrated'||style==='handleless')projection=Math.max(projection,t+25);return projection}

export function buildProject(project){
 const modules=layoutProject(project),parts=[],objects=[],warnings=[],issues=[];
 modules.forEach((m,index)=>{
  const w=m.width,h=m.height,d=m.depth,t=m.board,b=m.back,id=`M${String(index+1).padStart(2,'0')}`;
  const mb=moduleBounds(m),out=mb.x<0||mb.z<0||mb.x+mb.width>project.room.width||mb.z+mb.depth>project.room.depth||m.y+h>project.room.height;
  if(out&&!isRoomElementType(m.type)){issues.push({type:'module-out',moduleId:m.id,message:`${id}: модуль выходит за пределы комнаты.`});warnings.push(`${id}: модуль выходит за пределы комнаты.`)}
  if(isDisplayOnlyType(m.type)){displayGeometry(m,id,objects);return}
  const worktopFixture=(project.fixtures||[]).find(item=>item.targetModuleId===m.id),fixtureNeedsClearRail=['sink','hob'].includes(worktopFixture?.type),applianceBay=['washer','dishwasher'].includes(m.applianceBay),fullApplianceBay=applianceBay&&['base','sink'].includes(m.type),blindApplianceBay=applianceBay&&m.type==='cornerBaseBlind',appliance=applianceBay?applianceBayMeasurements(m,{...project.defaults,countertopDepth:project.countertop?.depth}):null,backOverlay=m.backMode==='overlay',bodyDepth=backOverlay?d-b:d,bottomUnder=m.bottomMode==='under',topOverlay=['wall','cornerWall','cornerWallBlind','cornerWallDiagonal','cornerWallL'].includes(m.type)&&m.topMode==='overlay',lower=bottomUnder?t:0,upper=topOverlay?t:0,sideH=h-lower-upper,inner=w-2*t,frontsEnabled=m.frontEnabled!==false&&!applianceBay,baseApp=appearance(m.bodyDecor,m.bodyColor,false),faceApp=appearance(m.frontDecor,m.frontColor,m.gloss,m.grain),blindOpening=Math.max(250,Math.min(m.cornerOpening||450,w-260)),blindOpeningSide=m.cornerOpeningSide==='left'?'left':'right',blindOpeningStart=blindOpeningSide==='left'?m.gap:w-m.gap-blindOpening,blindOpeningEnd=blindOpeningStart+blindOpening,blindSectionStart=blindOpeningSide==='left'?blindOpeningEnd:t,blindSectionEnd=blindOpeningSide==='left'?w-t:blindOpeningStart,blindSectionWidth=Math.max(0,blindSectionEnd-blindSectionStart),blindSectionX=(blindSectionStart+blindSectionEnd)/2;
  const add=(suffix,name,u,v,thick,edges,size,center,role='body',opts={})=>{const front=role==='front',raw=blankSize(u,v,edges),partId=`${id}-${suffix}`,decor=opts.decor||(front?m.frontDecor:m.bodyDecor),app=opts.appearance||(front?faceApp:baseApp),substrate=role==='back'?'mdf':front?m.frontSubstrate:m.bodySubstrate,materialProductId=role==='back'?'hdf3':front?(m.frontMaterialId||inferMaterialProductId({role:'front',substrate,gloss:app.gloss})):(m.bodyMaterialId||inferMaterialProductId({role:'body',substrate})),part={id:partId,moduleId:m.id,moduleCode:id,name,role,u:round(u),v:round(v),thickness:thick,blankU:raw[0],blankV:raw[1],edges,edgeType:front?m.frontEdgeType:m.bodyEdgeType,substrate,materialProductId,decor,grain:front?m.grain:'v',size,center:[center[0]+m.x,center[1]+m.y,center[2]+m.z],appearance:app,hingeSide:opts.hingeSide||null,hingeMountPartId:opts.hingeMountPartId||null,hingeType:opts.hingeType||null,rotationY:opts.rotationY||0};parts.push(part);objects.push({...part,kind:'part'});return part};
  const addBaseRails=(spanWidth,centerX)=>{if(fixtureNeedsClearRail)add('RF','Передняя вертикальная планка под вырез',spanWidth,100,t,[0,0,0,m.bodyEdge],[spanWidth,100,t],[centerX,h-50,d-t/2]);else add('RF','Передняя верхняя планка',spanWidth,100,t,[0,0,0,m.bodyEdge],[spanWidth,t,100],[centerX,h-t/2,d-50]);add('RR','Задняя верхняя планка',spanWidth,100,t,[0,0,0,0],[spanWidth,100,t],[centerX,h-50,(backOverlay?b:0)+t/2])};
  const addCornerFillers=()=>{
   if(m.feet<=20)return;
   const plinthHeight=m.feet-10,plinthSetback=65,frontHeight=Math.max(100,h-2*m.gap);
   for(const [side,width] of [['L',Number(m.cornerFillerLeft)||0],['R',Number(m.cornerFillerRight)||0]]){
   if(width<=0)continue;
    const left=side==='L',frontX=left?-width/2:w+width/2,returnLength=width+plinthSetback,returnX=left?-returnLength/2:w+returnLength/2;
    add(`CF${side}`,`${left?'Левый':'Правый'} угловой добор фасада`,width,frontHeight,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[width,frontHeight,m.frontThickness],[frontX,h/2,d+2+m.frontThickness/2],'front');
    if(m.legStyle==='hidden')add(`CP${side}`,`${left?'Левое':'Правое'} продолжение цоколя в угол`,returnLength,plinthHeight,t,[0,0,0,m.bodyEdge],[returnLength,plinthHeight,t],[returnX,-plinthHeight/2,d-plinthSetback]);
    const missingApplianceSupport=fullApplianceBay&&(left?!appliance.leftSupport:!appliance.rightSupport);
    if(missingApplianceSupport){const supportHeight=h+m.feet,supportCenterY=supportHeight/2-m.feet;add(`CS${side}`,`${left?'Левая':'Правая'} опорная стойка углового добора`,100,supportHeight,t,[0,0,0,0],[t,supportHeight,100],[left?-t/2:w+t/2,supportCenterY,d-50]);}
    warnings.push(`${id}: ${left?'левый':'правый'} угловой добор ${round(width)} мм и возврат цоколя ${round(returnLength)} мм включены в деталировку${missingApplianceSupport?`; за добором добавлена несущая стойка 100×${round(h+m.feet)} мм от пола до столешницы`:''}; крепёж добора проверить по месту.`);
   }
  };
  addCornerFillers();
  if(fullApplianceBay){
   const fullSideHeight=h+m.feet,sideCenterY=fullSideHeight/2-m.feet,opening=appliance.openingWidth,aw=appliance.applianceWidth,ah=appliance.applianceHeight,ad=appliance.applianceDepth,fits=appliance.fits;
   if(appliance.leftSupport)add('SL','Несущая боковина ниши левая',bodyDepth,fullSideHeight,t,[0,m.bodyEdge,0,0],[t,fullSideHeight,bodyDepth],[t/2,sideCenterY,(backOverlay?b:0)+bodyDepth/2]);
   if(appliance.rightSupport)add('SR','Несущая боковина ниши правая',bodyDepth,fullSideHeight,t,[0,m.bodyEdge,0,0],[t,fullSideHeight,bodyDepth],[w-t/2,sideCenterY,(backOverlay?b:0)+bodyDepth/2]);
   const openingStart=appliance.leftSupport?t:0,openingCenter=openingStart+opening/2,frontRailDrop=worktopFixture?.type==='hob'?Math.max(0,(Number(worktopFixture.installationHeight)||51)-(Number(worktopFixture.rimHeight)||6)-(Number(project.countertop?.thickness)||20)):0,decorativeGap=Math.max(3,appliance.topClearance),decorativeHeight=Math.max(0,appliance.availableHeight-ah-decorativeGap),hasDecorativeFiller=decorativeHeight>=18;
   add('FS','Передняя верхняя планка ниши (горизонтальная)',opening,100,t,[0,0,0,hasDecorativeFiller?0:m.bodyEdge],[opening,t,100],[openingCenter,h-frontRailDrop-t/2,d-50]);
   if(hasDecorativeFiller)add('AF','Съёмная декоративная планка над техникой',opening,decorativeHeight,m.frontThickness,[0,0,m.frontEdge,0],[opening,decorativeHeight,m.frontThickness],[openingCenter,h-decorativeHeight/2,d+2+m.frontThickness/2],'front');
   const rearBridgeLeft=!appliance.leftSupport?Math.max(0,Number(m.cornerFillerLeft)||0):0,rearBridgeRight=!appliance.rightSupport?Math.max(0,Number(m.cornerFillerRight)||0):0,rearSpan=opening+rearBridgeLeft+rearBridgeRight,rearCenter=openingStart-rearBridgeLeft+rearSpan/2;
   add('RS','Задняя верхняя планка ниши',rearSpan,100,t,[0,0,0,0],[rearSpan,100,t],[rearCenter,h-50,(backOverlay?b:0)+t/2]);
   embeddedApplianceGeometry(m,id,objects,(appliance.leftSupport?t:0)+(opening-aw)/2,Math.max(0,d-ad),!fits);
   if(!fits){const message=`${id}: техника ${aw}×${ah}×${ad} мм с боковым люфтом ${appliance.sideClearance} мм не помещается в чистый проём ${opening}×${appliance.availableHeight}×${appliance.availableDepth} мм: требуется ${appliance.requiredOpeningWidth} мм по ширине и ${ah+appliance.topClearance} мм по высоте.`;issues.push({type:'appliance-bay-fit',moduleId:m.id,message,required:{width:appliance.requiredOpeningWidth,height:ah+appliance.topClearance,depth:ad},available:{width:opening,height:appliance.availableHeight,depth:appliance.availableDepth}});warnings.push(message)}
   else warnings.push(`${id}: ниша ${opening} мм под ${m.applianceBay==='washer'?'стиральную':'посудомоечную'} машину; собственные опоры: ${appliance.leftSupport?'левая':''}${appliance.leftSupport&&appliance.rightSupport?' и ':''}${appliance.rightSupport?'правая':''}${!appliance.supportCount?'нет':''}. Дно, полки, фасад, цоколь и ножки в проёме отсутствуют; отсутствующие стороны должны опираться на соседний корпус. Передняя планка ${opening}×100 мм лежит горизонтально${frontRailDrop?` и опущена на ${round(frontRailDrop)} мм для корпуса варочной поверхности`:''}, задняя ${rearSpan}×100 мм установлена вертикально${rearBridgeLeft||rearBridgeRight?' и продлена через угловой добор до соседней боковины':''}${hasDecorativeFiller?`; спереди добавлена съёмная декоративная планка ${opening}×${round(decorativeHeight)} мм с кромкой только по видимому нижнему торцу`:''}.`);
   const fixture=worktopFixture;if(fixture?.type==='sink'){issues.push({type:'appliance-fixture-conflict',moduleId:m.id,fixtureId:fixture.id});warnings.push(`${id}: раковину нельзя размещать над стиральной или посудомоечной машиной в том же проёме.`)}else if(fixture?.type==='hob'){const hobDrop=Math.max(0,(Number(fixture.installationHeight)||51)-(Number(project.countertop?.thickness)||20)),clearance=appliance.availableHeight-ah-hobDrop;if(clearance<appliance.topClearance){issues.push({type:'appliance-hob-clearance',moduleId:m.id,fixtureId:fixture.id,clearance,required:appliance.topClearance});warnings.push(`${id}: корпус варочной поверхности выступает ниже столешницы на ${round(hobDrop)} мм; над техникой остаётся ${round(clearance)} мм вместо требуемых ${appliance.topClearance} мм.`)}else{const approved=m.applianceHobApproval===applianceHobApprovalSignature(m,fixture,project.countertop),message=approved?`${id}: сочетание варочной поверхности и ${m.applianceBay==='dishwasher'?'посудомоечной':'стиральной'} машины утверждено для текущих размеров. Между приборами установить совместимый теплозащитный/пароизоляционный экран и сохранить вентиляционный зазор.`:`${id}: геометрический зазор над техникой достаточен, но сочетание варочной поверхности и ${m.applianceBay==='dishwasher'?'посудомоечной':'стиральной'} машины нельзя выпускать в производство без подтверждения текущей компоновки${m.applianceBay==='dishwasher'?' и промежуточной защиты':''}.`;if(!approved)issues.push({type:'appliance-hob-compatibility',moduleId:m.id,fixtureId:fixture.id,applianceType:m.applianceBay,message});warnings.push(message)}};
   return;
  }
  add('SL','Боковина левая',bodyDepth,sideH,t,[0,m.bodyEdge,0,0],[t,sideH,bodyDepth],[t/2,lower+sideH/2,(backOverlay?b:0)+bodyDepth/2]);
  add('SR','Боковина правая',bodyDepth,sideH,t,[0,m.bodyEdge,0,0],[t,sideH,bodyDepth],[w-t/2,lower+sideH/2,(backOverlay?b:0)+bodyDepth/2]);
  if(blindApplianceBay){if(blindSectionWidth>40)add('BT','Дно глухой секции',blindSectionWidth,bodyDepth,t,[0,0,0,m.bodyEdge],[blindSectionWidth,t,bodyDepth],[blindSectionX,t/2,(backOverlay?b:0)+bodyDepth/2])}
  else if(bottomUnder)add('BT','Дно под боковинами',w,bodyDepth,t,[0,0,0,m.bodyEdge],[w,t,bodyDepth],[w/2,t/2,(backOverlay?b:0)+bodyDepth/2]);else add('BT','Дно между боковинами',inner,bodyDepth,t,[0,0,0,m.bodyEdge],[inner,t,bodyDepth],[w/2,t/2,(backOverlay?b:0)+bodyDepth/2]);
  if(m.backMode==='none'){}else if(backOverlay)add('BK','Задняя стенка накладная',w,h,b,[0,0,0,0],[w,h,b],[w/2,h/2,b/2],'back');else if(m.backMode==='inset')add('BK','Задняя стенка вкладная',inner,Math.max(40,h-lower-upper-2*t),b,[0,0,0,0],[inner,Math.max(40,h-lower-upper-2*t),b],[w/2,lower+(h-lower-upper)/2,b/2],'back');
  if(['wall','cornerWall','cornerWallBlind','cornerWallDiagonal','cornerWallL','tall','tallOven'].includes(m.type)){if(topOverlay)add('TP','Крышка сверху боковин',w,bodyDepth,t,[0,0,0,m.bodyEdge],[w,t,bodyDepth],[w/2,h-t/2,(backOverlay?b:0)+bodyDepth/2]);else add('TP','Верх между боковинами',inner,bodyDepth,t,[0,0,0,m.bodyEdge],[inner,t,bodyDepth],[w/2,h-t/2,(backOverlay?b:0)+bodyDepth/2])}
  else if(blindApplianceBay){if(blindSectionWidth>40){addBaseRails(blindSectionWidth,blindSectionX);if(m.feet>20&&m.legStyle==='hidden')add('PL','Цоколь глухой секции',blindSectionWidth,m.feet-10,t,[0,0,0,m.bodyEdge],[blindSectionWidth,m.feet-10,t],[blindSectionX,-(m.feet-10)/2,d-65])}}
  else{addBaseRails(inner,w/2);if(m.feet>20&&m.legStyle==='hidden')add('PL','Цоколь',w,m.feet-10,t,[0,0,0,m.bodyEdge],[w,m.feet-10,t],[w/2,-(m.feet-10)/2,d-65])}
  const supportObjects=buildCabinetSupportObjects(m,id);objects.push(...(blindApplianceBay?supportObjects.filter(object=>{const localX=object.center[0]-m.x;return localX<blindOpeningStart||localX>blindOpeningEnd}):supportObjects));
  if(!['sink','drawer'].includes(m.type)&&m.shelfCount>0){const sw=blindApplianceBay?blindSectionWidth:inner-2,sd=Math.max(80,bodyDepth-20),sx=blindApplianceBay?blindSectionX:w/2;if(sw>40)for(let s=0;s<m.shelfCount;s++){const sy=lower+(s+1)*(sideH/(m.shelfCount+1));add(`SH${s+1}`,blindApplianceBay?`Полка глухой секции ${s+1}`:`Полка ${s+1}`,sw,sd,t,[0,0,0,m.bodyEdge],[sw,t,sd],[sx,sy,(backOverlay?b:0)+sd/2])}}
  if(['cornerBaseBlind','cornerWallBlind'].includes(m.type)){
   const g=m.gap,opening=Math.max(250,Math.min(m.cornerOpening||450,w-260)),openingSide=m.cornerOpeningSide==='left'?'left':'right',fh=h-2*g,muntinDepth=Math.max(28,Math.min(Number(m.cornerMuntinWidth)||70,150,d-2*t)),blindW=Math.max(120,w-opening-4*g),start=openingSide==='left'?g:w-g-opening,blindX=openingSide==='left'?w-g-blindW/2:g+blindW/2,muntinX=openingSide==='left'?start+opening+g+t/2:start-g-t/2,muntinPartId=`${id}-MS`,sidePartId=`${id}-${openingSide==='left'?'SL':'SR'}`;
   add('BF','Глухая панель корпуса',blindW,fh,t,[m.bodyEdge,m.bodyEdge,m.bodyEdge,m.bodyEdge],[blindW,fh,t],[blindX,h/2,d-t/2],'body');
   add('MS','Монтажная перегородка петель',muntinDepth,fh,t,[0,m.bodyEdge,0,0],[t,fh,muntinDepth],[muntinX,h/2,d-muntinDepth/2],'body');
   if(frontsEnabled){const n=Math.max(1,Math.min(2,Number(m.doorCount)||1)),fw=(opening-(n-1)*g)/n;for(let j=0;j<n;j++){const x=start+fw/2+j*(fw+g),ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov),hingeSide=n===1?(openingSide==='left'?'right':'left'):(j===0?'left':'right'),mountPartId=n===1?muntinPartId:(openingSide==='left'?(j===0?sidePartId:muntinPartId):(j===0?muntinPartId:sidePartId)),hingeType=mountPartId===muntinPartId?'blind-corner-95':'overlay-110',front=add(`F${j+1}`,`Фасад ${j+1}`,fw,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[fw,fh,m.frontThickness],[x,h/2,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide,hingeMountPartId:mountPartId,hingeType});frontExtras(m,id,objects,x,h/2,d+m.frontThickness+4,fw,fh,hingeSide,front.id)}}
    if(blindApplianceBay){const aw=appliance.applianceWidth,ah=appliance.applianceHeight,ad=appliance.applianceDepth,fits=appliance.fits;embeddedApplianceGeometry(m,id,objects,start+(opening-aw)/2,Math.max(0,appliance.availableDepth-ad),!fits);if(!fits){const message=`${id}: техника с боковым люфтом ${appliance.sideClearance} мм не помещается в доступный угловой проём ${opening}×${appliance.availableHeight}×${appliance.availableDepth} мм.`;issues.push({type:'appliance-bay-fit',moduleId:m.id,message,required:{width:appliance.requiredOpeningWidth,height:ah+appliance.topClearance,depth:ad},available:{width:opening,height:appliance.availableHeight,depth:appliance.availableDepth}});warnings.push(message)}else warnings.push(`${id}: доступный проём ${opening} мм отдан под ${m.applianceBay==='washer'?'стиральную':'посудомоечную'} машину; дно, полки, фасад, цоколь и опоры оставлены только в глухой секции.`);const fixture=worktopFixture;if(fixture?.type==='sink'){issues.push({type:'appliance-fixture-conflict',moduleId:m.id,fixtureId:fixture.id});warnings.push(`${id}: раковина и техника не могут занимать один доступный угловой проём.`)}else if(fixture?.type==='hob'){const hobDrop=Math.max(0,(Number(fixture.installationHeight)||51)-(Number(project.countertop?.thickness)||20)),clearance=appliance.availableHeight-ah-hobDrop;if(clearance<appliance.topClearance){issues.push({type:'appliance-hob-clearance',moduleId:m.id,fixtureId:fixture.id,clearance,required:appliance.topClearance});warnings.push(`${id}: корпус варочной поверхности оставляет над техникой только ${round(clearance)} мм вместо ${appliance.topClearance} мм.`)}else{const approved=m.applianceHobApproval===applianceHobApprovalSignature(m,fixture,project.countertop),message=approved?`${id}: компоновка варочной поверхности над техникой утверждена для текущих размеров; установить совместимый теплозащитный экран.`:`${id}: варочная поверхность над техникой геометрически помещается, но компоновку нужно явно подтвердить вместе с промежуточной защитой.`;if(!approved)issues.push({type:'appliance-hob-compatibility',moduleId:m.id,fixtureId:fixture.id,applianceType:m.applianceBay,message});warnings.push(message)}}}
   warnings.push(`${id}: глухой угол — проём ${opening} мм ${openingSide==='left'?'слева':'справа'}, монтажная перегородка петель повёрнута перпендикулярно фасаду и входит в корпус на ${round(muntinDepth)} мм; проверить карту сверления выбранной фурнитуры.`);
  } else if(['cornerBaseDiagonal','cornerWallDiagonal'].includes(m.type)){
   const arm=Math.min(w,d,Number(m.cornerRunDepth)||Number(m.cornerWingDepth)||(m.type.includes('Wall')?320:600)),dx=w-arm,dz=arm-d,faceLen=Math.max(180,Math.hypot(dx,dz)),n=Math.max(1,Math.min(2,m.doorCount||1)),fh=h-2*m.gap,fw=(faceLen-(n+1)*m.gap)/n,rot=Math.atan2(d-arm,w-arm);
   if(frontsEnabled)for(let j=0;j<n;j++){const along=m.gap+fw/2+j*(fw+m.gap),q=along/faceLen,x=arm+dx*q,z=d+dz*q,ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov),hingeSide=ov.hingeSide||(n===1?'left':j===0?'left':'right');add(`F${j+1}`,`Диагональный фасад ${j+1}`,fw,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[fw,fh,m.frontThickness],[x,h/2,z],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide,rotationY:rot})}
   warnings.push(`${id}: диагональный корпус остаётся предварительным; фасад и его угол уже входят в деталировку, корпус проверить перед производством.`);
  } else if(['cornerBaseL','cornerWallL'].includes(m.type)){
   const arm=Math.min(w,d,Number(m.cornerRunDepth)||Number(m.cornerWingDepth)||(m.type.includes('Wall')?320:600)),fh=h-2*m.gap,lenX=Math.max(120,w-arm-m.gap),lenZ=Math.max(120,d-arm-m.gap),ovs=m.frontOverrides||[],ov1=ovs[0]||{},ov2=ovs[1]||{},finish1=frontFinish(m,ov1),finish2=frontFinish(m,ov2);
   if(frontsEnabled){add('F1','L-фасад 1',lenX,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[lenX,fh,m.frontThickness],[arm+lenX/2,h/2,arm+m.frontThickness/2],'front',{decor:finish1.decor,appearance:finish1.appearance,hingeSide:ov1.hingeSide||'right'});add('F2','L-фасад 2',lenZ,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[lenZ,fh,m.frontThickness],[arm+m.frontThickness/2,h/2,arm+lenZ/2],'front',{decor:finish2.decor,appearance:finish2.appearance,hingeSide:ov2.hingeSide||'left',rotationY:Math.PI/2})}
   warnings.push(`${id}: L-корпус остаётся предварительным; два фасада уже входят в деталировку, стык корпуса проверить перед производством.`);
  } else if(isDrawerType(m.type)){
   const n=Math.max(1,Math.min(6,m.drawerCount||3)),fh=(h-(n+1)*m.gap)/n;
   for(let j=0;j<n;j++){const y=m.gap+fh/2+j*(fh+m.gap),ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov);add(`F${j+1}`,`Фасад ящика ${j+1}`,w-2*m.gap,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[w-2*m.gap,fh,m.frontThickness],[w/2,y,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance});frontExtras(m,id,objects,w/2,y,d+m.frontThickness+4,w-2*m.gap,fh)}
   warnings.push(`${id}: показаны фасады ящиков; направляющие и короба ящиков пока не входят в напил.`)
  } else {
   const n=m.doorCount>0?m.doorCount:(w>650?2:1),totalW=w+m.frontOverhangLeft+m.frontOverhangRight,fw=(totalW-2*m.gap-(n-1)*m.gap)/n,fh=h+m.frontOverhangTop+m.frontOverhangBottom-2*m.gap,start=-m.frontOverhangLeft+m.gap;
   if(frontsEnabled)for(let j=0;j<n;j++){const x=start+fw/2+j*(fw+m.gap),y=h/2+(m.frontOverhangTop-m.frontOverhangBottom)/2,ov=(m.frontOverrides||[])[j]||{},finish=frontFinish(m,ov),hingeSide=ov.hingeSide||(n===1?'left':j===0?'left':j===n-1?'right':j%2?'right':'left'),front=add(`F${j+1}`,`Фасад ${j+1}`,fw,fh,m.frontThickness,[m.frontEdge,m.frontEdge,m.frontEdge,m.frontEdge],[fw,fh,m.frontThickness],[x,y,d+2+m.frontThickness/2],'front',{decor:finish.decor,appearance:finish.appearance,hingeSide});frontExtras(m,id,objects,x,y,d+m.frontThickness+4,fw,fh,hingeSide,front.id)}
  }
  if(isCornerType(m.type))warnings.push(`${id}: угловой модуль пока показан как параметрический габаритный корпус. Перед производством нужен отдельный профиль углового стыка/фасада.`);
  if(m.type==='tallOven')warnings.push(`${id}: ниша под духовку пока не вырезает корпус автоматически — высоту ниши нужно сверить по конкретной технике.`);
  if(m.width>900)warnings.push(`${id}: широкий пролёт; проверить прогиб и опоры.`);
  });
  const structuralModules=modules.filter(m=>!isDisplayOnlyType(m.type)&&!isRoomElementType(m.type));
  const sharedSupportAt=(module,side,distance=1)=>{
   const q=((Math.round((Number(module.rotationY)||0)/90)*90)%360+360)%360,r=q*Math.PI/180,cx=module.x+module.width/2,cz=module.z+module.depth/2,vx=Math.cos(r),vz=-Math.sin(r),sign=side==='left'?-1:1,px=cx+sign*vx*(module.width/2+distance),pz=cz+sign*vz*(module.width/2+distance),targetTop=module.y+module.height;
   const targetFloor=module.y-(Number(module.feet)||0);
   return structuralModules.some(other=>{if(other.id===module.id)return false;const bounds=moduleBounds(other),supportsPoint=px>=bounds.x-.01&&px<=bounds.x+bounds.width+.01&&pz>=bounds.z-.01&&pz<=bounds.z+bounds.depth+.01,otherTop=other.y+other.height,otherFloor=other.y-(Number(other.feet)||0);return supportsPoint&&otherFloor<=targetFloor+1&&otherTop>=targetTop-2});
  };
  for(const module of modules.filter(m=>['base','sink'].includes(m.type)&&['washer','dishwasher'].includes(m.applianceBay))){
   const measurements=applianceBayMeasurements(module,{...project.defaults,countertopDepth:project.countertop?.depth});
   for(const side of ['left','right']){
    const ownSupport=side==='left'?measurements.leftSupport:measurements.rightSupport;
    if(ownSupport)continue;
    const fillerWidth=Math.max(0,Number(side==='left'?module.cornerFillerLeft:module.cornerFillerRight)||0),fillerSupport=fillerWidth>0&&Number(module.feet)>20;
    if(fillerSupport&&sharedSupportAt(module,side,fillerWidth+1)){warnings.push(`${module.id}: ${side==='left'?'левая':'правая'} сторона ниши спереди опирается на скрытую стойку углового добора, а задняя планка продлена через добор на ${round(fillerWidth)} мм и соединяется с полноразмерной боковиной соседнего корпуса.`);continue}
    if(fillerSupport){const message=`${module.id}: за ${side==='left'?'левым':'правым'} угловым добором ${round(fillerWidth)} мм нет соседней полноразмерной боковины для крепления задней планки ниши.`;issues.push({type:'appliance-support-missing',moduleId:module.id,side,message});warnings.push(message);continue}
    if(sharedSupportAt(module,side))warnings.push(`${module.id}: ${side==='left'?'левая':'правая'} сторона ниши использует полноразмерную боковину соседнего корпуса как опору столешницы.`);
    else{const message=`${module.id}: у ${side==='left'?'левой':'правой'} стороны ниши нет ни собственной несущей боковины, ни примыкающего корпуса до столешницы.`;issues.push({type:'appliance-support-missing',moduleId:module.id,side,message});warnings.push(message)}
   }
  }
  for(const dishwasher of modules.filter(m=>['base','sink'].includes(m.type)&&m.applianceBay==='dishwasher')){
   const a=moduleBounds(dishwasher);
   for(const corner of structuralModules.filter(m=>m.id!==dishwasher.id&&isCornerType(m.type)&&!isWallMountedType(m.type))){
    const b=moduleBounds(corner),overlapX=Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x),overlapZ=Math.min(a.z+a.depth,b.z+b.depth)-Math.max(a.z,b.z),gaps=[];
    if(overlapX>0){if(a.z>=b.z+b.depth)gaps.push({body:a.z-(b.z+b.depth),x:0,z:1});else if(b.z>=a.z+a.depth)gaps.push({body:b.z-(a.z+a.depth),x:0,z:-1})}
    if(overlapZ>0){if(a.x>=b.x+b.width)gaps.push({body:a.x-(b.x+b.width),x:1,z:0});else if(b.x>=a.x+a.width)gaps.push({body:b.x-(a.x+a.width),x:-1,z:0})}
    if(!gaps.length)continue;
    const gap=gaps.sort((left,right)=>left.body-right.body)[0],cornerAngle=(Number(corner.rotationY)||0)*Math.PI/180,cornerForward={x:Math.sin(cornerAngle),z:Math.cos(cornerAngle)},dishwasherAngle=(Number(dishwasher.rotationY)||0)*Math.PI/180,dishwasherSide={x:Math.cos(dishwasherAngle),z:-Math.sin(dishwasherAngle)},cornerProjection=cornerForward.x*gap.x+cornerForward.z*gap.z>.5?cabinetFrontProjection(corner):0,measurements=applianceBayMeasurements(dishwasher,{...project.defaults,countertopDepth:project.countertop?.depth}),applianceInset=Math.abs(dishwasherSide.x*gap.x+dishwasherSide.z*gap.z)>.5?Math.max(0,(measurements.openingWidth-measurements.applianceWidth)/2):0,clearance=round(gap.body+applianceInset-cornerProjection),required=55;
    if(clearance<required){const message=`${dishwasher.id}: фактический боковой зазор открытой дверцы до углового фасада ${clearance} мм (между корпусами ${round(gap.body)} мм, отступ техники ${round(applianceInset)} мм, выступ углового фасада/ручки ${round(cornerProjection)} мм); требуется не менее ${required} мм с монтажным запасом.`;issues.push({type:'dishwasher-corner-clearance',moduleId:dishwasher.id,otherId:corner.id,clearance,required,bodyClearance:round(gap.body),applianceInset:round(applianceInset),cornerProjection:round(cornerProjection),message});warnings.push(message)}
    else if(clearance<100)warnings.push(`${dishwasher.id}: угловой зазор ${round(clearance)} мм проходит минимальную проверку открывания посудомоечной машины; окончательно сверить выступ ручки и фасад выбранной модели.`);
   }
  }
  const roomTypes=new Set(['window','door']),floor=modules.filter(m=>!isWallMountedType(m.type)&&!roomTypes.has(m.type)),baseTypes=new Set(['base','drawer','sink','cornerBase','cornerBaseBlind','cornerBaseDiagonal','cornerBaseL']),bases=floor.filter(m=>baseTypes.has(m.type)),top=project.countertop;
 for(let i=0;i<floor.length;i++)for(let j=i+1;j<floor.length;j++)if(rectsOverlap(floor[i],floor[j])){const a=floor[i],b=floor[j],cornerAppliance=(isCornerType(a.type)&&isApplianceType(b.type))||(isCornerType(b.type)&&isApplianceType(a.type)),message=cornerAppliance?'Техника пересекает угловой шкаф. Её нужно ставить отдельным проёмом или в предназначенный для неё модуль рядом, а не внутрь углового корпуса.':'Есть пересечение напольных модулей.';issues.push({type:cornerAppliance?'appliance-corner-overlap':'overlap',moduleId:a.id,otherId:b.id,message});warnings.push(message)}
 const autoStart=bases.length?Math.min(...bases.map(m=>m.x)):0,autoEnd=bases.length?Math.max(...bases.map(m=>m.x+m.width)):0,autoLength=Math.max(0,autoEnd-autoStart),topLength=top.lengthMode==='manual'?top.length:autoLength+2*top.overhang,topX=top.lengthMode==='manual'?top.offsetX:autoStart-top.overhang,topZ=Number.isFinite(top.offsetZ)?top.offsetZ:0,topY=Number.isFinite(top.elevation)?top.elevation:(bases.length?Math.max(...bases.map(m=>m.y+m.height)):860);
 let countertop=null;
 if(top.enabled&&bases.length){countertop={id:'CT-01',length:topLength,depth:top.depth,thickness:top.thickness,elevation:topY,x:topX,z:topZ};const ctOut=topX<0||topX+topLength>project.room.width||topZ<0||topZ+top.depth>project.room.depth||topY+top.thickness>project.room.height,uncovered=bases.some(m=>m.x<topX||m.x+m.width>topX+topLength||m.z<topZ||m.z+m.depth>topZ+top.depth);if(ctOut){issues.push({type:'countertop-out'});warnings.push('Столешница выходит за пределы комнаты.')}if(uncovered){issues.push({type:'countertop-cover'});warnings.push('Столешница не перекрывает все нижние шкафы.')}objects.push({id:'CT-01',kind:'countertop',role:'countertop',moduleId:null,size:[topLength,top.thickness,top.depth],center:[topX+topLength/2,topY+top.thickness/2,topZ+top.depth/2],appearance:appearance(top.decor,top.color,top.gloss),invalid:ctOut||uncovered})}
 if(countertop){const required=Math.max(5,Math.min(60,Number(project.defaults?.washerClearance)||10));for(const wm of modules.filter(m=>m.type==='washer')){const overlapX=wm.x<countertop.x+countertop.length&&wm.x+wm.width>countertop.x,overlapZ=wm.z<countertop.z+countertop.depth&&wm.z+wm.depth>countertop.z;if(overlapX&&overlapZ){const clearance=round(countertop.elevation-(wm.y+wm.height));if(clearance<required){issues.push({type:'washer-clearance',moduleId:wm.id,clearance,required});warnings.push(`Стиральная машина: зазор до низа столешницы ${clearance} мм, требуется минимум ${required} мм.`)}}}for(const bm of bases){const delta=round(countertop.elevation-(bm.y+bm.height));if(Math.abs(delta)>2)warnings.push(`${bm.type}: верх корпуса отличается от низа столешницы на ${delta} мм (корпус + ножки = ${bm.y+bm.height} мм).`)}}
 const fixtures=[];
 for(const f of project.fixtures||[]){const m=modules.find(x=>x.id===f.targetModuleId);if(!m)continue;const blind=m.type==='cornerBaseBlind',opening=blind?Math.max(250,Math.min(m.cornerOpening||450,m.width-260)):m.width,openingSide=m.cornerOpeningSide==='left'?'left':'right',openingStart=blind?(openingSide==='left'?m.gap:m.width-m.gap-opening):10,openingEnd=blind?openingStart+opening:m.width-10,baseX=blind?openingStart+opening/2:m.width/2,localX=baseX+f.offsetX,localZ=m.depth/2+f.offsetZ,x=m.x+localX,z=m.z+localZ,topY=(countertop?.elevation??(m.y+m.height))+(countertop?.thickness??top.thickness),installationHeight=Number(f.installationHeight)||(f.type==='sink'?200:51),rimHeight=Number(f.rimHeight)||6,y=topY+rimHeight/2,margin=blind?20:0,footprintFits=localX-f.width/2>=openingStart+margin&&localX+f.width/2<=openingEnd-margin&&localZ-f.depth/2>=10&&localZ+f.depth/2<=top.depth-10,fixtureBounds={x1:x-f.width/2,x2:x+f.width/2,y1:topY-Math.max(0,installationHeight-rimHeight),y2:topY+rimHeight,z1:z-f.depth/2,z2:z+f.depth/2},collisions=parts.filter(part=>part.moduleId===m.id&&part.role!=='front').filter(part=>{const [pw,ph,pd]=part.size,[px,py,pz]=part.center;return fixtureBounds.x1<px+pw/2&&fixtureBounds.x2>px-pw/2&&fixtureBounds.y1<py+ph/2&&fixtureBounds.y2>py-ph/2&&fixtureBounds.z1<pz+pd/2&&fixtureBounds.z2>pz-pd/2}),fits=footprintFits&&collisions.length===0;fixtures.push({...f,installationHeight,rimHeight,x,y,z,worktopTopY:topY,fits,collisions:collisions.map(part=>part.id)});objects.push({id:f.id,moduleId:m.id,kind:f.type==='sink'?'fixture-sink':'fixture-hob',role:'fixture',size:[f.width,installationHeight,f.depth],center:[x,y,z],installationHeight,rimHeight,appearance:appearance('graphite',f.type==='sink'?'#aeb7b9':'#161d20'),invalid:!fits});if(!footprintFits){issues.push({type:'fixture',fixtureId:f.id,moduleId:m.id});warnings.push(`${f.type==='sink'?'Раковина':'Варочная поверхность'} не помещается${blind?' в доступный проём глухого углового модуля':''}.`)}if(collisions.length){issues.push({type:'fixture-part-collision',fixtureId:f.id,moduleId:m.id,partIds:collisions.map(part=>part.id)});warnings.push(`${f.type==='sink'?'Корпус раковины':'Корпус варочной поверхности'} пересекает детали ${collisions.map(part=>part.id).join(', ')}. Измени вырез, глубину элемента или конструкцию планок.`)}}
 for(const hood of modules.filter(m=>m.type==='hood')){const bounds=moduleBounds(hood),hob=fixtures.find(f=>f.type==='hob'&&f.x>=bounds.x&&f.x<=bounds.x+bounds.width&&f.z>=bounds.z&&f.z<=bounds.z+bounds.depth);if(!hob)continue;const clearance=round(hood.y-hob.worktopTopY),required=500;if(clearance<required){const message=`Вытяжка ${hood.id}: от верха столешницы до низа вытяжки ${clearance} мм, для принятого предварительного режима индукционной панели требуется не менее ${required} мм; паспорт конкретной модели может требовать больше.`;issues.push({type:'hood-clearance',moduleId:hood.id,fixtureId:hob.id,clearance,required,message});warnings.push(message)}else warnings.push(`Вытяжка ${hood.id}: монтажный просвет ${clearance} мм проходит предварительную проверку для индукционной панели; окончательное расстояние взять из паспорта выбранной вытяжки и варочной поверхности.`)}
 warnings.push('Предварительная деталировка: крепёж, сверление, петли, направляющие, нагрузки и припуски цеха требуют проверки.');
 const minX=Math.min(0,...modules.map(m=>m.x)),maxX=Math.max(project.room.width,...modules.map(m=>m.x+m.width));
 return{modules,parts,objects,warnings:[...new Set(warnings)],issues,fixtures,countertop,width:Math.max(0,maxX-minX),height:Math.max(900,...modules.map(m=>m.y+m.height)),depth:Math.max(620,...modules.map(m=>m.z+m.depth+(m.frontThickness||0)+2))};
}
