import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,dirname,relative,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),ordered=[],seen=new Set(),visiting=new Set();
const imports=/^import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?\s*$/gm;
function key(file){return relative(root,file).split(sep).join('/');}
async function visit(file){
 if(seen.has(file))return;if(visiting.has(file))throw new Error('Circular import: '+file);visiting.add(file);
 const text=await readFile(file,'utf8'),matches=[...text.matchAll(imports)];
 for(const m of matches){const dep=resolve(dirname(file),m[2]);if(!dep.startsWith(root+sep))throw new Error('Import outside project');await visit(dep);}
 const names=[...text.matchAll(/^export\s+(?:async\s+)?(?:function|class|const|let)\s+(\w+)/gm)].map(m=>m[1]);
 const body=text.replace(imports,(_all,names,path)=>`const { ${names.replace(/\s+as\s+/g,': ')} } = __modules[${JSON.stringify(key(resolve(dirname(file),path)))}];`).replace(/^export\s+(?=(?:async\s+)?(?:function|class|const|let)\b)/gm,'');
 ordered.push(`__modules[${JSON.stringify(key(file))}] = (() => {\n${body}\nreturn {${names.join(',')}};\n})();`);visiting.delete(file);seen.add(file);
}
await visit(resolve(root,'src/ui/app.js'));
const js=`/* Kitchen CAD 0.1.0 · generated by scripts/build.mjs */\n(() => { 'use strict'; const __modules = Object.create(null);\n${ordered.join('\n')}\n})();`;
const css=await readFile(resolve(root,'src/ui/style.css'),'utf8');
let html=await readFile(resolve(root,'index.html'),'utf8');
html=html.replace('<link rel="stylesheet" href="./src/ui/style.css">',`<style>${css}</style>`).replace('<script type="module" src="./src/ui/app.js"></script>',`<script>${js.replace(/<\/script/gi,'<\\/script')}</script>`);
await mkdir(resolve(root,'dist'),{recursive:true});await writeFile(resolve(root,'dist/index.html'),html);await writeFile(resolve(root,'dist/.nojekyll'),'');
await writeFile(resolve(root,'dist/app.bundle.js'),js);
console.log(`Built ${ordered.length} modules; standalone HTML: ${Buffer.byteLength(html)} bytes. No remote assets.`);
