import { RoundedBox } from '@react-three/drei';
import { Edges } from '@react-three/drei';
const mm=(v:number)=>v/1000;
export function ApplianceVisual({module,selected=false,dimmed=false}:{module:any;selected?:boolean;dimmed?:boolean}){
  const w=mm(module.width),h=mm(module.height),d=mm(module.depth),opacity=dimmed?.14:1;
  const body=<RoundedBox args={[w,h,d]} radius={.025} smoothness={4} position={[w/2,h/2,d/2]} castShadow receiveShadow><meshStandardMaterial color="#d8dcde" roughness={.32} metalness={.12} transparent={dimmed} opacity={opacity}/>{selected&&<Edges color="#34d4e5" lineWidth={2}/>}</RoundedBox>;
  if(module.type==='washer')return <group>{body}<mesh position={[w/2,h*.72,d+.008]}><boxGeometry args={[w*.88,h*.11,.025]}/><meshStandardMaterial color="#c1c8cb" roughness={.25}/></mesh><mesh position={[w*.69,h*.72,d+.024]}><boxGeometry args={[w*.18,h*.05,.018]}/><meshStandardMaterial color="#17242a" roughness={.12}/></mesh><mesh position={[w/2,h*.43,d+.035]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[w*.22,w*.035,14,48]}/><meshStandardMaterial color="#9da7aa" metalness={.65} roughness={.24}/></mesh><mesh position={[w/2,h*.43,d+.04]} rotation={[Math.PI/2,0,0]}><circleGeometry args={[w*.185,48]}/><meshPhysicalMaterial color="#15242b" roughness={.12} transmission={.22}/></mesh></group>;
  if(module.type==='oven')return <group>{body}<mesh position={[w/2,h*.43,d+.018]}><boxGeometry args={[w*.84,h*.55,.035]}/><meshPhysicalMaterial color="#0c1418" roughness={.08} transmission={.12}/></mesh><mesh position={[w/2,h*.83,d+.025]}><boxGeometry args={[w*.82,h*.12,.025]}/><meshStandardMaterial color="#343e42" metalness={.45} roughness={.22}/></mesh><mesh position={[w/2,h*.67,d+.055]}><boxGeometry args={[w*.62,.025,.035]}/><meshStandardMaterial color="#b8c0c2" metalness={.8} roughness={.2}/></mesh></group>;
  if(module.type==='dishwasher')return <group>{body}<mesh position={[w/2,h*.5,d+.016]}><boxGeometry args={[w*.91,h*.87,.03]}/><meshStandardMaterial color="#b7bec0" metalness={.55} roughness={.25}/></mesh><mesh position={[w/2,h*.88,d+.05]}><boxGeometry args={[w*.58,.022,.035]}/><meshStandardMaterial color="#525d61" metalness={.65} roughness={.22}/></mesh></group>;
  if(module.type==='fridge')return <group>{body}<mesh position={[w/2,h*.68,d+.016]}><boxGeometry args={[w*.91,h*.58,.03]}/><meshStandardMaterial color="#c3c9cb" metalness={.35} roughness={.3}/></mesh><mesh position={[w/2,h*.2,d+.016]}><boxGeometry args={[w*.91,h*.34,.03]}/><meshStandardMaterial color="#bcc3c5" metalness={.35} roughness={.3}/></mesh><mesh position={[w*.88,h*.68,d+.05]}><boxGeometry args={[.024,h*.2,.035]}/><meshStandardMaterial color="#4c565a" metalness={.6}/></mesh><mesh position={[w*.88,h*.2,d+.05]}><boxGeometry args={[.024,h*.13,.035]}/><meshStandardMaterial color="#4c565a" metalness={.6}/></mesh></group>;
  return body;
}
