import { useEffect,useMemo,useRef,useState } from 'react';
import { Canvas,useThree } from '@react-three/fiber';
import { Edges,Grid,Html,Line,OrbitControls } from '@react-three/drei';
import * as THREE from 'three';
import { proceduralTexture } from './materials';
import { ApplianceVisual } from './ApplianceVisual';
import { explodedCentre } from '../domain/view-math.js';
import type { DimensionDetail,Selection } from '../domain/core';
const mm=(v:number)=>v/1000,appliances=new Set(['washer','dishwasher','oven','fridge']);
function pointOnPlane(e:any,y:number){return e.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-y),new THREE.Vector3())}
function Surface({object,selected=false,onSelect}:{object:any;selected?:boolean;onSelect?:()=>void}){const size=object.size.map(mm) as [number,number,number],local=object.localCenter.map(mm) as [number,number,number],a=object.appearance||{},texture=useMemo(()=>proceduralTexture(a.pattern,a.color),[a.pattern,a.color]),glass=object.kind==='front-insert';if(object.shape==='disc')return null;return <mesh position={local} onPointerDown={e=>{if(onSelect){e.stopPropagation();onSelect()}}}><boxGeometry args={size}/><meshStandardMaterial map={texture||undefined} color={texture?'#fff':(a.color||'#ccc')} roughness={glass?.2:(a.gloss?.25:.58)} metalness={object.kind==='handle'?.35:.02} transparent={glass} opacity={glass?.55:1}/>{selected&&<Edges color="#9a75ff" lineWidth={2}/>}</mesh>}
function ModuleVisual({module,objects,selected,selectedPartId,focus,detail,explode,onSelect,onSelectPart,onCommitPosition,onDragChange}:{module:any;objects:any[];selected:boolean;selectedPartId:string|null;focus:boolean;detail:DimensionDetail;explode:number;onSelect:()=>void;onSelectPart:(id:string)=>void;onCommitPosition:(x:number,z:number)=>void;onDragChange:(v:boolean)=>void}){const group=useRef<THREE.Group>(null!),dragging=useRef(false),offset=useRef({x:0,z:0}),{invalidate}=useThree(),detailMode=detail!=='none'&&selected&&!appliances.has(module.type),localObjects=useMemo(()=>objects.map(o=>{const c=detailMode?explodedCentre(o,module,explode):o.center;return{...o,localCenter:[c[0]-module.x,c[1]-module.y,c[2]-module.z]}}),[objects,module,detailMode,explode]),visibleObjects=detailMode?localObjects.filter(o=>o.kind==='part'):localObjects,hidden=focus&&!selected;
const down=(e:any)=>{e.stopPropagation();if(!selected){onSelect();return}if(detailMode)return;const p=pointOnPlane(e,mm(module.y));if(!p)return;dragging.current=true;onDragChange(true);offset.current={x:group.current.position.x-p.x,z:group.current.position.z-p.z};e.target.setPointerCapture?.(e.pointerId)};
const move=(e:any)=>{if(!dragging.current)return;e.stopPropagation();const p=pointOnPlane(e,mm(module.y));if(!p)return;group.current.position.x=Math.round((p.x+offset.current.x)*20)/20;group.current.position.z=Math.round((p.z+offset.current.z)*20)/20;invalidate()};
const up=(e:any)=>{if(!dragging.current)return;e.stopPropagation();dragging.current=false;onDragChange(false);e.target.releasePointerCapture?.(e.pointerId);onCommitPosition(group.current.position.x*1000,group.current.position.z*1000)};
return <group ref={group} visible={!hidden} position={[mm(module.x),mm(module.y),mm(module.z)]} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{appliances.has(module.type)?<ApplianceVisual module={module} selected={selected}/>:<>{visibleObjects.map((o:any)=><group key={o.id}><Surface object={o} selected={selectedPartId===o.id} onSelect={detailMode?()=>onSelectPart(o.id):undefined}/></group>)}{selected&&<mesh position={[mm(module.width/2),mm(module.height/2),mm(module.depth/2)]}><boxGeometry args={[mm(module.width),mm(module.height),mm(module.depth)]}/><meshBasicMaterial transparent opacity={0}/><Edges color="#34d4e5" lineWidth={2}/></mesh>}{detailMode&&visibleObjects.map((o:any,i:number)=><Html key={`b-${o.id}`} position={o.localCenter.map(mm)} center><button className={selectedPartId===o.id?'partBadge active':'partBadge'} onClick={ev=>{ev.stopPropagation();onSelectPart(o.id)}}>{i+1}</button></Html>)}</>}</group>}
function Countertop({object,selected,focus,onSelect,onCommit,onDragChange}:{object:any;selected:boolean;focus:boolean;onSelect:()=>void;onCommit:(x:number,z:number)=>void;onDragChange:(v:boolean)=>void}){const group=useRef<THREE.Group>(null!),dragging=useRef(false),offset=useRef({x:0,z:0}),{invalidate}=useThree(),size=object.size.map(mm) as [number,number,number],pos=object.center.map(mm) as [number,number,number],texture=useMemo(()=>proceduralTexture(object.appearance?.pattern,object.appearance?.color),[object.appearance?.pattern,object.appearance?.color]);const down=(e:any)=>{e.stopPropagation();if(!selected){onSelect();return}const p=pointOnPlane(e,pos[1]);if(!p)return;dragging.current=true;onDragChange(true);offset.current={x:group.current.position.x-p.x,z:group.current.position.z-p.z};e.target.setPointerCapture?.(e.pointerId)};const move=(e:any)=>{if(!dragging.current)return;e.stopPropagation();const p=pointOnPlane(e,pos[1]);if(!p)return;group.current.position.x=Math.round((p.x+offset.current.x)*20)/20;group.current.position.z=Math.round((p.z+offset.current.z)*20)/20;invalidate()};const up=(e:any)=>{if(!dragging.current)return;e.stopPropagation();dragging.current=false;onDragChange(false);e.target.releasePointerCapture?.(e.pointerId);onCommit((group.current.position.x-size[0]/2)*1000,(group.current.position.z-size[2]/2)*1000)};return <group ref={group} visible={!focus} position={pos} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><mesh><boxGeometry args={size}/><meshStandardMaterial map={texture||undefined} color={texture?'#fff':object.appearance?.color||'#dedbd2'} roughness={.3}/>{selected&&<Edges color="#9a75ff" lineWidth={2}/>}</mesh></group>}
function Dimension({a,b,label}:{a:[number,number,number];b:[number,number,number];label:string}){const mid:[number,number,number]=[(a[0]+b[0])/2,(a[1]+b[1])/2,(a[2]+b[2])/2];return <><Line points={[a,b]} color="#6d54d9" lineWidth={1}/><Html position={mid} center><span className="dimLabel">{label}</span></Html></>}
function Dimensions({model,selection}:{model:any;selection:Selection}){if(!selection||selection.kind==='part')return null;if(selection.kind==='countertop'){const o=model.objects.find((x:any)=>x.id==='CT-01');if(!o)return null;const[x,y,z]=o.center.map(mm),[w,h,d]=o.size.map(mm);return <><Dimension a={[x-w/2,y+h/2+.04,z+d/2]} b={[x+w/2,y+h/2+.04,z+d/2]} label={`${Math.round(o.size[0])} мм`}/><Dimension a={[x+w/2+.04,y,z-d/2]} b={[x+w/2+.04,y,z+d/2]} label={`${Math.round(o.size[2])} мм`}/></>};const m=model.modules.find((x:any)=>x.id===selection.id);if(!m)return null;const x=mm(m.x),y=mm(m.y),z=mm(m.z),w=mm(m.width),h=mm(m.height),d=mm(m.depth);return <><Dimension a={[x,y+h+.045,z+d]} b={[x+w,y+h+.045,z+d]} label={`${m.width} мм`}/><Dimension a={[x+w+.04,y,z+d]} b={[x+w+.04,y+h,z+d]} label={`${m.height} мм`}/><Dimension a={[x+w+.075,y+.03,z]} b={[x+w+.075,y+.03,z+d]} label={`${m.depth} мм`}/></>}
function CameraRig({project,model,focusId,dragging}:{project:any;model:any;focusId:string|null;dragging:boolean}){const{camera}=useThree(),controls=useRef<any>(null),target=useMemo(()=>{const m=focusId?model.modules.find((x:any)=>x.id===focusId):null;return m?new THREE.Vector3(mm(m.x+m.width/2),mm(m.y+m.height/2),mm(m.z+m.depth/2)):new THREE.Vector3(mm(project.room.width/2),.65,mm(project.room.depth/3))},[focusId,model,project.room.width,project.room.depth]);useEffect(()=>{if(focusId){camera.position.set(target.x+.95,target.y+.62,target.z+1.05);camera.lookAt(target)}if(controls.current){controls.current.target.copy(target);controls.current.update()}},[focusId,target,camera]);return <OrbitControls ref={controls} makeDefault enabled={!dragging} enableDamping={false} rotateSpeed={.95} zoomSpeed={1} panSpeed={.8} minPolarAngle={.08} maxPolarAngle={Math.PI/2.02} minDistance={.45} maxDistance={9} touches={{ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN}}/>}
function SceneContent(props:any){const{project,model,selection,setSelection,focusId,detail,onMoveModule,onMoveCountertop}=props,[dragging,setDragging]=useState(false),selectedModuleId=selection?.kind==='module'?selection.id:selection?.kind==='part'?selection.moduleId:null,selectedPartId=selection?.kind==='part'?selection.id:null,explode=detail==='none'?0:(project.ui?.explode||0);return <><color attach="background" args={[project.ui?.theme==='light'?'#dfe6e8':'#10171b']}/><hemisphereLight args={['#ffffff','#485a63',1.5]}/><directionalLight position={[3.5,5,4]} intensity={1.55}/><mesh rotation={[-Math.PI/2,0,0]} position={[mm(project.room.width/2),0,mm(project.room.depth/2)]} onPointerDown={e=>{if(dragging)return;e.stopPropagation();setSelection(null)}}><planeGeometry args={[mm(project.room.width),mm(project.room.depth)]}/><meshStandardMaterial color={project.room.floorColor} roughness={.85}/></mesh>{!focusId&&<><mesh position={[mm(project.room.width/2),mm(project.room.height/2),-.012]}><boxGeometry args={[mm(project.room.width),mm(project.room.height),.02]}/><meshStandardMaterial color={project.room.wallColor} roughness={.92}/></mesh><mesh position={[-.012,mm(project.room.height/2),mm(project.room.depth/2)]}><boxGeometry args={[.02,mm(project.room.height),mm(project.room.depth)]}/><meshStandardMaterial color={project.room.wallColor} roughness={.92}/></mesh></>}{model.modules.map((m:any)=><ModuleVisual key={m.id} module={m} objects={model.objects.filter((o:any)=>o.moduleId===m.id)} selected={selectedModuleId===m.id} selectedPartId={selectedPartId} focus={!!focusId} detail={detail} explode={explode} onSelect={()=>setSelection({kind:'module',id:m.id})} onSelectPart={(id:string)=>setSelection({kind:'part',id,moduleId:m.id})} onCommitPosition={(x,z)=>onMoveModule(m.id,x,z)} onDragChange={setDragging}/>)}{model.objects.find((o:any)=>o.id==='CT-01')&&<Countertop object={model.objects.find((o:any)=>o.id==='CT-01')} selected={selection?.kind==='countertop'} focus={!!focusId} onSelect={()=>setSelection({kind:'countertop',id:'CT-01'})} onCommit={onMoveCountertop} onDragChange={setDragging}/>}<Dimensions model={model} selection={selection}/>{project.ui?.showGrid!==false&&<Grid args={[7,7]} cellSize={.1} sectionSize={.5} cellColor="#617179" sectionColor="#82939b" fadeDistance={6} infiniteGrid position={[0,.001,0]}/>}<CameraRig project={project} model={model} focusId={focusId} dragging={dragging}/></>}
export function KitchenScene(props:any){return <Canvas frameloop="demand" dpr={[1,1.25]} camera={{position:[2.7,2.1,3.05],fov:43}} gl={{antialias:true,powerPreference:'high-performance'}} onPointerMissed={()=>props.setSelection(null)}><SceneContent {...props}/></Canvas>}
